load("//bazel:py_rules.bzl", "py_test")

package(default_visibility = ["//visibility:public"])

py_test(
    name = "parallelize_test",
    srcs = ["parallelize_test.py"],
    tags = [
        "feature:core",
        "short_regress",
    ],
    deps = [
        "//snowflake/ml/_internal/utils:connection_params",
        "//snowflake/ml/_internal/utils:parallelize",
        "//tests/integ/snowflake/ml/modeling/framework:utils",
    ],
)
