estimator_info_list = [
    struct(class_name = "AffinityPropagation", normalized_class_name = "affinity_propagation"),
    struct(class_name = "AgglomerativeClustering", normalized_class_name = "agglomerative_clustering"),
    struct(class_name = "Birch", normalized_class_name = "birch"),
    struct(class_name = "BisectingKMeans", normalized_class_name = "bisecting_k_means"),
    struct(class_name = "DBSCAN", normalized_class_name = "dbscan"),
    struct(class_name = "FeatureAgglomeration", normalized_class_name = "feature_agglomeration"),
    struct(class_name = "KMeans", normalized_class_name = "k_means"),
    struct(class_name = "MeanShift", normalized_class_name = "mean_shift"),
    struct(class_name = "MiniBatchKMeans", normalized_class_name = "mini_batch_k_means"),
    struct(class_name = "OPTICS", normalized_class_name = "optics"),
    struct(class_name = "SpectralBiclustering", normalized_class_name = "spectral_biclustering"),
    struct(class_name = "SpectralClustering", normalized_class_name = "spectral_clustering"),
    struct(class_name = "SpectralCoclustering", normalized_class_name = "spectral_coclustering"),
]
