"""SQL generators for tile-based aggregations.

This module provides SQL generation for:
1. TilingSqlGenerator: Creates the DT query that computes partial aggregations (tiles)
2. MergingSqlGenerator: Creates the CTEs for merging tiles during dataset generation
3. RollupSqlGenerator: Creates the DT query for rolling up tiles to a coarser entity level
"""

from __future__ import annotations

from collections.abc import Sequence
from typing import Optional

from snowflake.ml._internal.utils.sql_identifier import SqlIdentifier
from snowflake.ml.feature_store.aggregation import (
    AggregationSpec,
    AggregationType,
    interval_to_seconds,
    parse_interval,
)

# Maximum number of elements to store in array columns to avoid 128MB limit
# Assuming ~1KB per value, 100,000 values ≈ 100MB (leaving buffer)
_MAX_ARRAY_ELEMENTS = 100000

# Internal column names used in tile tables and merging SQL.
# These are generated by the tiling process and are not user-facing columns.
# WARNING: Changing these will break existing registered tiled feature views.
_TILE_START_COL = "TILE_START"
_TILE_BOUNDARY_COL = "TILE_BOUNDARY"


class TilingSqlGenerator:
    """Generates SQL for creating tile Dynamic Tables.

    The tiling query:
    1. Computes TIME_SLICE to bucket rows into tiles
    2. Computes partial aggregations per (join_keys, tile_start)
    3. For simple aggregations: stores SUM/COUNT as scalars
    4. For list aggregations: stores pre-sorted arrays (ARRAY_AGG with ORDER BY)
    5. For secondary key aggregations: stores scalar partials grouped by (join_keys, secondary_key, tile_start);
       array_agg across secondary keys is deferred to the merge step
    """

    def __init__(
        self,
        source_query: str,
        join_keys: Sequence[str],
        timestamp_col: str,
        feature_granularity: str,
        features: list[AggregationSpec],
    ) -> None:
        """Initialize the TilingSqlGenerator.

        Args:
            source_query: The source query providing raw event data.
            join_keys: Column names used as join keys (from entities).
            timestamp_col: The timestamp column name.
            feature_granularity: The tile interval (e.g., "1h", "1d").
            features: List of aggregation specifications.
        """
        self._source_query = source_query
        self._join_keys = join_keys
        self._timestamp_col = timestamp_col
        self._feature_granularity = feature_granularity
        self._features = features

        # Derive the FV-level secondary key from the synthesized keys-specs
        # (each carries ``source_column = secondary_key``).
        self._secondary_key: Optional[str] = next(
            (s.source_column for s in features if s.function.is_secondary_key_array()),
            None,
        )

        # Parse interval for SQL generation
        self._interval_value, self._interval_unit = parse_interval(feature_granularity)

        # Track if we have any lifetime features (need cumulative columns)
        self._has_lifetime_features = any(f.is_lifetime() for f in features)

    def generate(self) -> str:
        """Generate the complete tiling SQL query.

        Returns:
            SQL query for creating the tile Dynamic Table.
        """
        if self._secondary_key is not None:
            return self._generate_secondary_key_query()

        tile_columns = self._generate_tile_columns()
        # Join keys and timestamp_col are already properly formatted by SqlIdentifier
        join_keys_str = ", ".join(self._join_keys)
        ts_col = self._timestamp_col

        if not self._has_lifetime_features:
            # Simple case: no lifetime features, just partial aggregations
            query = f"""
SELECT
    {join_keys_str},
    TIME_SLICE({ts_col}, {self._interval_value}, '{self._interval_unit}', 'START') AS {_TILE_START_COL},
    {', '.join(tile_columns)}
FROM ({self._source_query})
GROUP BY {join_keys_str}, {_TILE_START_COL}
"""
        else:
            # With lifetime features: need cumulative columns via window functions
            # Structure: SELECT *, cumulative_columns FROM (SELECT partial_columns GROUP BY)
            cumulative_columns = self._generate_cumulative_columns()

            query = f"""
SELECT
    base.*,
    {', '.join(cumulative_columns)}
FROM (
    SELECT
        {join_keys_str},
        TIME_SLICE({ts_col}, {self._interval_value}, '{self._interval_unit}', 'START') AS {_TILE_START_COL},
        {', '.join(tile_columns)}
    FROM ({self._source_query})
    GROUP BY {join_keys_str}, {_TILE_START_COL}
) base
"""
        return query.strip()

    def _generate_secondary_key_query(self) -> str:
        """Generate the tile query when the FV has an aggregation secondary key.

        Tiles are scalar partials grouped by
        ``(join_keys..., secondary_key, TILE_START)``. Re-aggregation across
        secondary keys (``ARRAY_AGG``) is deferred to the merge step.

        Returns:
            SQL query for tile Dynamic Table creation.
        """
        assert self._secondary_key is not None  # invariant: gated by caller
        join_keys_str = ", ".join(self._join_keys)
        ts_col = self._timestamp_col
        secondary_key = self._secondary_key

        tile_columns = self._generate_tile_columns()

        query = f"""
SELECT
    {join_keys_str},
    {secondary_key},
    TIME_SLICE({ts_col}, {self._interval_value}, '{self._interval_unit}', 'START') AS {_TILE_START_COL},
    {', '.join(tile_columns)}
FROM ({self._source_query})
GROUP BY {join_keys_str}, {secondary_key}, {_TILE_START_COL}
"""
        return query.strip()

    def _generate_tile_columns(self) -> list[str]:
        """Generate the tile column expressions for all features.

        All simple aggregations share base partial columns:
        - _PARTIAL_SUM_{col}: SUM(col) - used by SUM, AVG, STD, VAR
        - _PARTIAL_COUNT_{col}: COUNT(col) - used by COUNT, AVG, STD, VAR
        - _PARTIAL_SUM_SQ_{col}: SUM(col*col) - used by STD, VAR

        This allows maximum column reuse. For example, SUM(amount) + AVG(amount)
        only creates 2 columns, not 3.

        Returns:
            List of SQL column expressions for the tile table.
        """
        # Track unique tile columns by their full name to avoid duplicates
        seen_columns: set[str] = set()
        columns = []
        ts_col = self._timestamp_col

        for spec in self._features:
            # _SECONDARY_KEY_ARRAY specs have no tile partials
            if spec.function.is_secondary_key_array():
                continue
            src_col = spec.source_column

            if spec.function == AggregationType.SUM:
                # SUM needs _PARTIAL_SUM
                col_name = spec.get_tile_column_name("SUM")
                if col_name not in seen_columns:
                    columns.append(f"SUM({src_col}) AS {col_name}")
                    seen_columns.add(col_name)

            elif spec.function == AggregationType.COUNT:
                # COUNT needs _PARTIAL_COUNT
                col_name = spec.get_tile_column_name("COUNT")
                if col_name not in seen_columns:
                    columns.append(f"COUNT({src_col}) AS {col_name}")
                    seen_columns.add(col_name)

            elif spec.function == AggregationType.AVG:
                # AVG needs _PARTIAL_SUM and _PARTIAL_COUNT
                sum_col = spec.get_tile_column_name("SUM")
                count_col = spec.get_tile_column_name("COUNT")
                if sum_col not in seen_columns:
                    columns.append(f"SUM({src_col}) AS {sum_col}")
                    seen_columns.add(sum_col)
                if count_col not in seen_columns:
                    columns.append(f"COUNT({src_col}) AS {count_col}")
                    seen_columns.add(count_col)

            elif spec.function == AggregationType.MIN:
                # MIN needs _PARTIAL_MIN
                col_name = spec.get_tile_column_name("MIN")
                if col_name not in seen_columns:
                    columns.append(f"MIN({src_col}) AS {col_name}")
                    seen_columns.add(col_name)

            elif spec.function == AggregationType.MAX:
                # MAX needs _PARTIAL_MAX
                col_name = spec.get_tile_column_name("MAX")
                if col_name not in seen_columns:
                    columns.append(f"MAX({src_col}) AS {col_name}")
                    seen_columns.add(col_name)

            elif spec.function in (AggregationType.STD, AggregationType.VAR):
                # STD/VAR need _PARTIAL_SUM, _PARTIAL_COUNT, and _PARTIAL_SUM_SQ
                sum_col = spec.get_tile_column_name("SUM")
                count_col = spec.get_tile_column_name("COUNT")
                sum_sq_col = spec.get_tile_column_name("SUM_SQ")
                if sum_col not in seen_columns:
                    columns.append(f"SUM({src_col}) AS {sum_col}")
                    seen_columns.add(sum_col)
                if count_col not in seen_columns:
                    columns.append(f"COUNT({src_col}) AS {count_col}")
                    seen_columns.add(count_col)
                if sum_sq_col not in seen_columns:
                    columns.append(f"SUM({src_col} * {src_col}) AS {sum_sq_col}")
                    seen_columns.add(sum_sq_col)

            elif spec.function == AggregationType.APPROX_COUNT_DISTINCT:
                # APPROX_COUNT_DISTINCT uses HLL (HyperLogLog) state
                col_name = spec.get_tile_column_name("HLL")
                if col_name not in seen_columns:
                    columns.append(f"HLL_EXPORT(HLL_ACCUMULATE({src_col})) AS {col_name}")
                    seen_columns.add(col_name)

            elif spec.function == AggregationType.APPROX_PERCENTILE:
                # APPROX_PERCENTILE uses T-Digest state
                col_name = spec.get_tile_column_name("TDIGEST")
                if col_name not in seen_columns:
                    columns.append(f"APPROX_PERCENTILE_ACCUMULATE({src_col}) AS {col_name}")
                    seen_columns.add(col_name)

            elif spec.function == AggregationType.LAST_N:
                col_name = spec.get_tile_column_name("LAST")
                if col_name not in seen_columns:
                    columns.append(
                        f"ARRAY_SLICE("
                        f"ARRAY_AGG({src_col}) WITHIN GROUP (ORDER BY {ts_col} DESC), "
                        f"0, {_MAX_ARRAY_ELEMENTS}) AS {col_name}"
                    )
                    seen_columns.add(col_name)
                # Companion timestamp array for rollup ordering
                ts_col_name = spec.get_tile_column_name("LAST_TS")
                if ts_col_name not in seen_columns:
                    columns.append(
                        f"ARRAY_SLICE("
                        f"ARRAY_AGG({ts_col}) WITHIN GROUP (ORDER BY {ts_col} DESC), "
                        f"0, {_MAX_ARRAY_ELEMENTS}) AS {ts_col_name}"
                    )
                    seen_columns.add(ts_col_name)

            elif spec.function == AggregationType.LAST_DISTINCT_N:
                # Uses same tile column as LAST_N (dedup happens at merge time)
                col_name = spec.get_tile_column_name("LAST")
                if col_name not in seen_columns:
                    columns.append(
                        f"ARRAY_SLICE("
                        f"ARRAY_AGG({src_col}) WITHIN GROUP (ORDER BY {ts_col} DESC), "
                        f"0, {_MAX_ARRAY_ELEMENTS}) AS {col_name}"
                    )
                    seen_columns.add(col_name)
                # Companion timestamp array for rollup ordering
                ts_col_name = spec.get_tile_column_name("LAST_TS")
                if ts_col_name not in seen_columns:
                    columns.append(
                        f"ARRAY_SLICE("
                        f"ARRAY_AGG({ts_col}) WITHIN GROUP (ORDER BY {ts_col} DESC), "
                        f"0, {_MAX_ARRAY_ELEMENTS}) AS {ts_col_name}"
                    )
                    seen_columns.add(ts_col_name)

            elif spec.function == AggregationType.FIRST_N:
                col_name = spec.get_tile_column_name("FIRST")
                if col_name not in seen_columns:
                    columns.append(
                        f"ARRAY_SLICE("
                        f"ARRAY_AGG({src_col}) WITHIN GROUP (ORDER BY {ts_col} ASC), "
                        f"0, {_MAX_ARRAY_ELEMENTS}) AS {col_name}"
                    )
                    seen_columns.add(col_name)
                # Companion timestamp array for rollup ordering
                ts_col_name = spec.get_tile_column_name("FIRST_TS")
                if ts_col_name not in seen_columns:
                    columns.append(
                        f"ARRAY_SLICE("
                        f"ARRAY_AGG({ts_col}) WITHIN GROUP (ORDER BY {ts_col} ASC), "
                        f"0, {_MAX_ARRAY_ELEMENTS}) AS {ts_col_name}"
                    )
                    seen_columns.add(ts_col_name)

            elif spec.function == AggregationType.FIRST_DISTINCT_N:
                # Uses same tile column as FIRST_N (dedup happens at merge time)
                col_name = spec.get_tile_column_name("FIRST")
                if col_name not in seen_columns:
                    columns.append(
                        f"ARRAY_SLICE("
                        f"ARRAY_AGG({src_col}) WITHIN GROUP (ORDER BY {ts_col} ASC), "
                        f"0, {_MAX_ARRAY_ELEMENTS}) AS {col_name}"
                    )
                    seen_columns.add(col_name)
                # Companion timestamp array for rollup ordering
                ts_col_name = spec.get_tile_column_name("FIRST_TS")
                if ts_col_name not in seen_columns:
                    columns.append(
                        f"ARRAY_SLICE("
                        f"ARRAY_AGG({ts_col}) WITHIN GROUP (ORDER BY {ts_col} ASC), "
                        f"0, {_MAX_ARRAY_ELEMENTS}) AS {ts_col_name}"
                    )
                    seen_columns.add(ts_col_name)

        return columns

    def _generate_cumulative_columns(self) -> list[str]:
        """Generate cumulative column expressions for lifetime aggregations.

        These columns use window functions to compute running totals per entity.
        They are computed over the partial columns from the inner GROUP BY.

        Returns:
            List of SQL column expressions for cumulative columns.
        """
        lifetime_features = [f for f in self._features if f.is_lifetime()]
        return _generate_cumulative_expressions(lifetime_features, list(self._join_keys))


def _generate_cumulative_expressions(
    lifetime_specs: list[AggregationSpec],
    join_keys: list[str],
) -> list[str]:
    """Generate cumulative window function expressions for lifetime aggregations.

    Produces SQL column expressions that compute running aggregates over
    ``_PARTIAL_*`` columns, partitioned by ``join_keys`` and ordered by
    ``TILE_START``.  Used by both ``TilingSqlGenerator`` (for base tile DTs)
    and ``RollupSqlGenerator`` (for rolled-up tile DTs / CTEs).

    Only SUM, COUNT, AVG, MIN, MAX, STD, VAR are supported (sketch and list
    types are rejected by ``AggregationSpec.validate()``).

    Args:
        lifetime_specs: Aggregation specs with ``is_lifetime() == True``.
        join_keys: Entity key columns for the PARTITION BY clause.

    Returns:
        List of SQL column expressions, e.g.
        ``"SUM(_PARTIAL_COUNT_X) OVER (...) AS _CUM_COUNT_X"``.
    """
    seen_columns: set[str] = set()
    columns: list[str] = []
    join_keys_str = ", ".join(join_keys)

    for spec in lifetime_specs:
        if spec.function == AggregationType.SUM:
            partial_col = spec.get_tile_column_name("SUM")
            cum_col = spec.get_cumulative_column_name("SUM")
            if cum_col not in seen_columns:
                columns.append(
                    f"SUM({partial_col}) OVER ("
                    f"PARTITION BY {join_keys_str} "
                    f"ORDER BY {_TILE_START_COL} "
                    f"ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW"
                    f") AS {cum_col}"
                )
                seen_columns.add(cum_col)

        elif spec.function == AggregationType.COUNT:
            partial_col = spec.get_tile_column_name("COUNT")
            cum_col = spec.get_cumulative_column_name("COUNT")
            if cum_col not in seen_columns:
                columns.append(
                    f"SUM({partial_col}) OVER ("
                    f"PARTITION BY {join_keys_str} "
                    f"ORDER BY {_TILE_START_COL} "
                    f"ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW"
                    f") AS {cum_col}"
                )
                seen_columns.add(cum_col)

        elif spec.function == AggregationType.AVG:
            partial_sum = spec.get_tile_column_name("SUM")
            partial_count = spec.get_tile_column_name("COUNT")
            cum_sum = spec.get_cumulative_column_name("SUM")
            cum_count = spec.get_cumulative_column_name("COUNT")

            if cum_sum not in seen_columns:
                columns.append(
                    f"SUM({partial_sum}) OVER ("
                    f"PARTITION BY {join_keys_str} "
                    f"ORDER BY {_TILE_START_COL} "
                    f"ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW"
                    f") AS {cum_sum}"
                )
                seen_columns.add(cum_sum)
            if cum_count not in seen_columns:
                columns.append(
                    f"SUM({partial_count}) OVER ("
                    f"PARTITION BY {join_keys_str} "
                    f"ORDER BY {_TILE_START_COL} "
                    f"ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW"
                    f") AS {cum_count}"
                )
                seen_columns.add(cum_count)

        elif spec.function == AggregationType.MIN:
            partial_col = spec.get_tile_column_name("MIN")
            cum_col = spec.get_cumulative_column_name("MIN")
            if cum_col not in seen_columns:
                columns.append(
                    f"MIN({partial_col}) OVER ("
                    f"PARTITION BY {join_keys_str} "
                    f"ORDER BY {_TILE_START_COL} "
                    f"ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW"
                    f") AS {cum_col}"
                )
                seen_columns.add(cum_col)

        elif spec.function == AggregationType.MAX:
            partial_col = spec.get_tile_column_name("MAX")
            cum_col = spec.get_cumulative_column_name("MAX")
            if cum_col not in seen_columns:
                columns.append(
                    f"MAX({partial_col}) OVER ("
                    f"PARTITION BY {join_keys_str} "
                    f"ORDER BY {_TILE_START_COL} "
                    f"ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW"
                    f") AS {cum_col}"
                )
                seen_columns.add(cum_col)

        elif spec.function in (AggregationType.STD, AggregationType.VAR):
            partial_sum = spec.get_tile_column_name("SUM")
            partial_count = spec.get_tile_column_name("COUNT")
            partial_sum_sq = spec.get_tile_column_name("SUM_SQ")
            cum_sum = spec.get_cumulative_column_name("SUM")
            cum_count = spec.get_cumulative_column_name("COUNT")
            cum_sum_sq = spec.get_cumulative_column_name("SUM_SQ")

            if cum_sum not in seen_columns:
                columns.append(
                    f"SUM({partial_sum}) OVER ("
                    f"PARTITION BY {join_keys_str} "
                    f"ORDER BY {_TILE_START_COL} "
                    f"ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW"
                    f") AS {cum_sum}"
                )
                seen_columns.add(cum_sum)
            if cum_count not in seen_columns:
                columns.append(
                    f"SUM({partial_count}) OVER ("
                    f"PARTITION BY {join_keys_str} "
                    f"ORDER BY {_TILE_START_COL} "
                    f"ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW"
                    f") AS {cum_count}"
                )
                seen_columns.add(cum_count)
            if cum_sum_sq not in seen_columns:
                columns.append(
                    f"SUM({partial_sum_sq}) OVER ("
                    f"PARTITION BY {join_keys_str} "
                    f"ORDER BY {_TILE_START_COL} "
                    f"ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW"
                    f") AS {cum_sum_sq}"
                )
                seen_columns.add(cum_sum_sq)

    return columns


class MergingSqlGenerator:
    """Generates CTEs for merging tiles during dataset generation.

    The merging process:
    1. TILES_JOINED_FVi: Join tiles with spine, filtering by window and complete tiles only
    2. SIMPLE_MERGED_FVi: Aggregate simple features (SUM, COUNT, AVG)
    3. LIST_MERGED_FVi: Flatten and aggregate list features (LAST_N, etc.)
    4. SECONDARY_KEY_MERGED_FVi: Merge secondary key arrays across tiles
    5. FVi: Combine simple, list, and secondary key results
    """

    def __init__(
        self,
        tile_table: str,
        join_keys: Sequence[str],
        timestamp_col: str,
        feature_granularity: str,
        features: list[AggregationSpec],
        spine_timestamp_col: str,
        fv_index: int,
    ) -> None:
        """Initialize the MergingSqlGenerator.

        Args:
            tile_table: Fully qualified name of the tile table.
            join_keys: Join key column names.
            timestamp_col: The timestamp column from the feature view.
            feature_granularity: The tile interval.
            features: List of aggregation specifications.
            spine_timestamp_col: The timestamp column from the spine.
            fv_index: Index of this feature view (for CTE naming).
        """
        self._tile_table = tile_table
        self._join_keys = join_keys
        self._timestamp_col = timestamp_col
        self._feature_granularity = feature_granularity
        self._features = features
        self._spine_timestamp_col = spine_timestamp_col
        self._fv_index = fv_index

        # Derive the FV-level secondary key from synthesized keys-specs.
        self._secondary_key: Optional[str] = next(
            (s.source_column for s in features if s.function.is_secondary_key_array()),
            None,
        )

        # Separate keys / lifetime / non-lifetime value features.
        self._keys_specs: list[AggregationSpec] = [f for f in features if f.function.is_secondary_key_array()]
        value_features = [f for f in features if not f.function.is_secondary_key_array()]
        self._lifetime_features = [f for f in value_features if f.is_lifetime()]
        self._non_lifetime_features = [f for f in value_features if not f.is_lifetime()]

        # When an FV-level secondary key is set, every non-lifetime value feature
        # flows through the secondary-key merge path (per-(entity, sk)
        # re-aggregation + ARRAY_AGG by sk).
        if self._secondary_key is not None:
            self._secondary_key_features = list(self._non_lifetime_features)
            self._simple_features: list[AggregationSpec] = []
            self._list_features: list[AggregationSpec] = []
        else:
            self._secondary_key_features = []
            self._simple_features = [f for f in self._non_lifetime_features if f.function.is_simple()]
            self._list_features = [f for f in self._non_lifetime_features if f.function.is_list()]

        # Lifetime features are all simple (validation ensures only SUM, COUNT, AVG, MIN, MAX, STD, VAR)
        self._lifetime_simple_features = self._lifetime_features

        # Parse interval
        self._interval_value, self._interval_unit = parse_interval(feature_granularity)
        self._interval_seconds = interval_to_seconds(feature_granularity)

        # Calculate max window in tiles for filtering (only for non-lifetime features)
        if self._non_lifetime_features:
            # Max tiles needed is the max of (window + offset) across all non-lifetime features
            max_lookback_seconds = max(
                f.get_window_seconds() + f.get_offset_seconds() for f in self._non_lifetime_features
            )
            self._max_tiles_needed = (max_lookback_seconds + self._interval_seconds - 1) // self._interval_seconds
        else:
            self._max_tiles_needed = 0

    def generate_all_ctes(self) -> list[tuple[str, str]]:
        """Generate all CTEs needed for this feature view.

        The optimization flow:
        1. SPINE_BOUNDARY: Add truncated tile boundary to spine
        2. UNIQUE_BOUNDS: Get distinct (entity, boundary) pairs
        3. TILES_JOINED: Join tiles to unique boundaries (for non-lifetime features)
        4. SIMPLE_MERGED: Aggregate simple non-lifetime features per boundary
        5. LIST_MERGED: Aggregate list non-lifetime features per boundary
        6. SECONDARY_KEY_MERGED: Merge secondary key arrays across tiles
        7. LIFETIME_MERGED: ASOF JOIN for lifetime features (O(1) per boundary)
        8. FV: Join back to spine to expand results

        Returns:
            List of (cte_name, cte_body) tuples.
        """
        ctes = []

        # CTE 1: Spine with tile boundary (for join-back)
        ctes.append(self._generate_spine_boundary_cte())

        # CTE 2: Unique boundaries (optimization - reduce aggregation work)
        ctes.append(self._generate_unique_boundaries_cte())

        # CTE 3: Join tiles with unique boundaries (only if we have non-lifetime features)
        if self._non_lifetime_features:
            ctes.append(self._generate_tiles_joined_cte())

        # CTE 4: Simple aggregations (if any non-lifetime)
        if self._simple_features:
            ctes.append(self._generate_simple_merged_cte())

        # CTE 5: List aggregations (if any non-lifetime)
        if self._list_features:
            ctes.append(self._generate_list_merged_cte())

        # CTE 6: Secondary key aggregations (merge arrays across tiles)
        if self._secondary_key_features:
            ctes.append(self._generate_secondary_key_merged_cte())

        # CTE 7: Lifetime simple aggregations (using ASOF JOIN on cumulative columns)
        if self._lifetime_simple_features:
            ctes.append(self._generate_lifetime_merged_cte())

        # CTE 8: Combine all results and join back to spine
        ctes.append(self._generate_combined_cte())

        return ctes

    def _generate_spine_boundary_cte(self) -> tuple[str, str]:
        """Generate CTE that adds tile boundary to deduplicated spine.

        The tile boundary is the truncated timestamp that determines which
        complete tiles are visible. All spine rows with the same boundary
        will have identical feature values.

        Returns:
            Tuple of (cte_name, cte_body).
        """
        cte_name = f"SPINE_BOUNDARY_FV{self._fv_index}"

        join_keys = self._join_keys
        spine_ts = self._spine_timestamp_col

        # Select all columns plus the tile boundary
        all_cols = list(join_keys) + [spine_ts]
        select_cols = ", ".join(all_cols)

        # DATE_TRUNC to tile granularity gives us the boundary
        # All timestamps in the same granularity window see the same complete tiles
        cte_body = f"""
    SELECT DISTINCT {select_cols},
           DATE_TRUNC('{self._interval_unit.lower()}', {spine_ts}) AS {_TILE_BOUNDARY_COL}
    FROM SPINE
"""
        return cte_name, cte_body.strip()

    def _generate_unique_boundaries_cte(self) -> tuple[str, str]:
        """Generate CTE with unique (entity, boundary) pairs.

        This is the key optimization: instead of computing features for each
        spine row, we compute once per unique boundary and join back.

        Returns:
            Tuple of (cte_name, cte_body).
        """
        cte_name = f"UNIQUE_BOUNDS_FV{self._fv_index}"

        keys_str = ", ".join(self._join_keys)

        cte_body = f"""
    SELECT DISTINCT {keys_str}, {_TILE_BOUNDARY_COL}
    FROM SPINE_BOUNDARY_FV{self._fv_index}
"""
        return cte_name, cte_body.strip()

    def _generate_tiles_joined_cte(self) -> tuple[str, str]:
        """Generate the CTE that joins tiles with unique boundaries.

        This joins tiles to UNIQUE_BOUNDS (not full spine), which is much smaller
        when there are many spine rows per tile boundary.

        Returns:
            Tuple of (cte_name, cte_body) for the tiles joined CTE.
        """
        cte_name = f"TILES_JOINED_FV{self._fv_index}"

        tile_keys_str = ", ".join(self._join_keys)

        # Join conditions between spine (UB) and tile columns
        join_conditions = [f"UB.{k} = TILES.{k}" for k in self._join_keys]

        # Get all tile columns we need (deduplicated)
        tile_columns_set: set[str] = set()
        for spec in self._features:
            if spec.function == AggregationType.SUM:
                tile_columns_set.add(spec.get_tile_column_name("SUM"))
            elif spec.function == AggregationType.COUNT:
                tile_columns_set.add(spec.get_tile_column_name("COUNT"))
            elif spec.function == AggregationType.AVG:
                tile_columns_set.add(spec.get_tile_column_name("SUM"))
                tile_columns_set.add(spec.get_tile_column_name("COUNT"))
            elif spec.function == AggregationType.MIN:
                tile_columns_set.add(spec.get_tile_column_name("MIN"))
            elif spec.function == AggregationType.MAX:
                tile_columns_set.add(spec.get_tile_column_name("MAX"))
            elif spec.function in (AggregationType.STD, AggregationType.VAR):
                tile_columns_set.add(spec.get_tile_column_name("SUM"))
                tile_columns_set.add(spec.get_tile_column_name("COUNT"))
                tile_columns_set.add(spec.get_tile_column_name("SUM_SQ"))
            elif spec.function == AggregationType.APPROX_COUNT_DISTINCT:
                tile_columns_set.add(spec.get_tile_column_name("HLL"))
            elif spec.function == AggregationType.APPROX_PERCENTILE:
                tile_columns_set.add(spec.get_tile_column_name("TDIGEST"))
            elif spec.function in (AggregationType.LAST_N, AggregationType.LAST_DISTINCT_N):
                tile_columns_set.add(spec.get_tile_column_name("LAST"))
            elif spec.function in (AggregationType.FIRST_N, AggregationType.FIRST_DISTINCT_N):
                tile_columns_set.add(spec.get_tile_column_name("FIRST"))
        if self._secondary_key is not None and self._secondary_key_features:
            tile_columns_set.add(self._secondary_key)
        tile_columns = sorted(tile_columns_set)  # Sort for deterministic output

        tile_columns_str = ", ".join(f"TILES.{col}" for col in tile_columns)

        # Window filter: only include tiles within the max window and complete tiles
        # Complete tiles: tile_end <= tile_boundary (not spine timestamp)
        # tile_end = DATEADD(interval_unit, interval_value, tile_start)
        cte_body = f"""
    SELECT
        UB.*,
        TILES.{_TILE_START_COL},
        {tile_columns_str}
    FROM UNIQUE_BOUNDS_FV{self._fv_index} UB
    LEFT JOIN (
        SELECT {tile_keys_str}, {_TILE_START_COL}, {', '.join(tile_columns)}
        FROM {self._tile_table}
    ) TILES
    ON {' AND '.join(join_conditions)}
    -- Window filter: tiles within max window from tile boundary
    AND TILES.{_TILE_START_COL} >= DATEADD(
        {self._interval_unit}, -{self._max_tiles_needed * self._interval_value}, UB.{_TILE_BOUNDARY_COL}
    )
    -- Complete tiles only: tile_end <= tile_boundary
    AND DATEADD({self._interval_unit}, {self._interval_value}, TILES.{_TILE_START_COL}) <= UB.{_TILE_BOUNDARY_COL}
"""
        return cte_name, cte_body.strip()

    def _get_tile_filter_condition(self, spec: AggregationSpec) -> str:
        """Generate the CASE WHEN condition for filtering tiles by window and offset.

        For a feature with window W and offset O, we want tiles where:
        - TILE_START >= TILE_BOUNDARY - W - O (start of window)
        - TILE_START < TILE_BOUNDARY - O (end of window, before offset)

        Args:
            spec: The aggregation specification.

        Returns:
            SQL condition string for use in CASE WHEN.
        """
        window_tiles = (spec.get_window_seconds() + self._interval_seconds - 1) // self._interval_seconds
        offset_tiles = spec.get_offset_seconds() // self._interval_seconds

        if offset_tiles == 0:
            # No offset: just filter by window start
            return (
                f"{_TILE_START_COL} >= DATEADD({self._interval_unit}, "
                f"-{window_tiles * self._interval_value}, {_TILE_BOUNDARY_COL})"
            )
        else:
            # With offset: filter by both window start and end (shifted by offset)
            window_start_tiles = window_tiles + offset_tiles
            return (
                f"{_TILE_START_COL} >= DATEADD({self._interval_unit}, "
                f"-{window_start_tiles * self._interval_value}, {_TILE_BOUNDARY_COL}) "
                f"AND {_TILE_START_COL} < DATEADD({self._interval_unit}, "
                f"-{offset_tiles * self._interval_value}, {_TILE_BOUNDARY_COL})"
            )

    def _get_list_tile_filter_condition(self, spec: AggregationSpec) -> str:
        """Generate filter condition for list aggregations (with table prefix).

        Similar to _get_tile_filter_condition but uses t. prefix for table references.

        Args:
            spec: The aggregation specification.

        Returns:
            SQL condition string for use in WHERE clause.
        """
        window_tiles = (spec.get_window_seconds() + self._interval_seconds - 1) // self._interval_seconds
        offset_tiles = spec.get_offset_seconds() // self._interval_seconds

        if offset_tiles == 0:
            # No offset: just filter by window start
            return (
                f"t.{_TILE_START_COL} >= DATEADD({self._interval_unit}, "
                f"-{window_tiles * self._interval_value}, t.{_TILE_BOUNDARY_COL})"
            )
        else:
            # With offset: filter by both window start and end (shifted by offset)
            window_start_tiles = window_tiles + offset_tiles
            return (
                f"t.{_TILE_START_COL} >= DATEADD({self._interval_unit}, "
                f"-{window_start_tiles * self._interval_value}, t.{_TILE_BOUNDARY_COL}) "
                f"AND t.{_TILE_START_COL} < DATEADD({self._interval_unit}, "
                f"-{offset_tiles * self._interval_value}, t.{_TILE_BOUNDARY_COL})"
            )

    def _generate_simple_merged_cte(self) -> tuple[str, str]:
        """Generate the CTE for simple aggregations (SUM, COUNT, AVG).

        Groups by entity keys + TILE_BOUNDARY (not spine timestamp) for efficiency.

        Returns:
            Tuple of (cte_name, cte_body) for the simple merged CTE.
        """
        cte_name = f"SIMPLE_MERGED_FV{self._fv_index}"

        # Group by entity keys + TILE_BOUNDARY (optimization)
        group_by_cols = list(self._join_keys) + [_TILE_BOUNDARY_COL]
        group_by_str = ", ".join(group_by_cols)

        agg_columns = []
        for spec in self._simple_features:
            output_col = spec.get_sql_column_name()
            tile_filter = self._get_tile_filter_condition(spec)

            if spec.function == AggregationType.SUM:
                col_name = spec.get_tile_column_name("SUM")
                agg_columns.append(f"SUM(CASE WHEN {tile_filter} " f"THEN {col_name} ELSE 0 END) AS {output_col}")

            elif spec.function == AggregationType.COUNT:
                col_name = spec.get_tile_column_name("COUNT")
                agg_columns.append(f"SUM(CASE WHEN {tile_filter} " f"THEN {col_name} ELSE 0 END) AS {output_col}")

            elif spec.function == AggregationType.MIN:
                col_name = spec.get_tile_column_name("MIN")
                agg_columns.append(f"MIN(CASE WHEN {tile_filter} " f"THEN {col_name} ELSE NULL END) AS {output_col}")

            elif spec.function == AggregationType.MAX:
                col_name = spec.get_tile_column_name("MAX")
                agg_columns.append(f"MAX(CASE WHEN {tile_filter} " f"THEN {col_name} ELSE NULL END) AS {output_col}")

            elif spec.function == AggregationType.AVG:
                # AVG = SUM(partial_sums) / SUM(partial_counts)
                sum_col = spec.get_tile_column_name("SUM")
                count_col = spec.get_tile_column_name("COUNT")
                agg_columns.append(
                    f"CASE WHEN SUM(CASE WHEN {tile_filter} "
                    f"THEN {count_col} ELSE 0 END) > 0 "
                    f"THEN SUM(CASE WHEN {tile_filter} "
                    f"THEN {sum_col} ELSE 0 END) / "
                    f"SUM(CASE WHEN {tile_filter} "
                    f"THEN {count_col} ELSE 0 END) "
                    f"ELSE NULL END AS {output_col}"
                )

            elif spec.function == AggregationType.VAR:
                # VAR = (SUM_SQ / COUNT) - (SUM / COUNT)^2
                # Using parallel variance formula
                # GREATEST(0, ...) clamps to non-negative to handle floating-point errors
                sum_col = spec.get_tile_column_name("SUM")
                count_col = spec.get_tile_column_name("COUNT")
                sum_sq_col = spec.get_tile_column_name("SUM_SQ")
                agg_columns.append(
                    f"CASE WHEN SUM(CASE WHEN {tile_filter} "
                    f"THEN {count_col} ELSE 0 END) > 0 "
                    f"THEN GREATEST(0, ("
                    f"SUM(CASE WHEN {tile_filter} "
                    f"THEN {sum_sq_col} ELSE 0 END) / "
                    f"SUM(CASE WHEN {tile_filter} "
                    f"THEN {count_col} ELSE 0 END)"
                    f") - POWER("
                    f"SUM(CASE WHEN {tile_filter} "
                    f"THEN {sum_col} ELSE 0 END) / "
                    f"SUM(CASE WHEN {tile_filter} "
                    f"THEN {count_col} ELSE 0 END), 2)) "
                    f"ELSE NULL END AS {output_col}"
                )

            elif spec.function == AggregationType.STD:
                # STD = SQRT(VAR) = SQRT((SUM_SQ / COUNT) - (SUM / COUNT)^2)
                # GREATEST(0, ...) clamps variance to non-negative to handle floating-point errors
                # that can cause sqrt of tiny negative numbers like -4.54747e-13
                sum_col = spec.get_tile_column_name("SUM")
                count_col = spec.get_tile_column_name("COUNT")
                sum_sq_col = spec.get_tile_column_name("SUM_SQ")
                agg_columns.append(
                    f"CASE WHEN SUM(CASE WHEN {tile_filter} "
                    f"THEN {count_col} ELSE 0 END) > 0 "
                    f"THEN SQRT(GREATEST(0, "
                    f"SUM(CASE WHEN {tile_filter} "
                    f"THEN {sum_sq_col} ELSE 0 END) / "
                    f"SUM(CASE WHEN {tile_filter} "
                    f"THEN {count_col} ELSE 0 END)"
                    f" - POWER("
                    f"SUM(CASE WHEN {tile_filter} "
                    f"THEN {sum_col} ELSE 0 END) / "
                    f"SUM(CASE WHEN {tile_filter} "
                    f"THEN {count_col} ELSE 0 END), 2))) "
                    f"ELSE NULL END AS {output_col}"
                )

            elif spec.function == AggregationType.APPROX_COUNT_DISTINCT:
                # Combine HLL states and estimate count
                # HLL_ESTIMATE(HLL_COMBINE(HLL_IMPORT(state))) gives the approximate count
                col_name = spec.get_tile_column_name("HLL")
                agg_columns.append(
                    f"HLL_ESTIMATE(HLL_COMBINE("
                    f"CASE WHEN {tile_filter} THEN HLL_IMPORT({col_name}) ELSE NULL END"
                    f")) AS {output_col}"
                )

            elif spec.function == AggregationType.APPROX_PERCENTILE:
                # Combine T-Digest states and estimate percentile
                # APPROX_PERCENTILE_ESTIMATE(APPROX_PERCENTILE_COMBINE(state), percentile)
                col_name = spec.get_tile_column_name("TDIGEST")
                percentile = spec.params.get("percentile", 0.5)
                agg_columns.append(
                    f"APPROX_PERCENTILE_ESTIMATE(APPROX_PERCENTILE_COMBINE("
                    f"CASE WHEN {tile_filter} THEN {col_name} ELSE NULL END"
                    f"), {percentile}) AS {output_col}"
                )

        cte_body = f"""
    SELECT
        {group_by_str},
        {', '.join(agg_columns)}
    FROM TILES_JOINED_FV{self._fv_index}
    GROUP BY {group_by_str}
"""
        return cte_name, cte_body.strip()

    def _generate_list_merged_cte(self) -> tuple[str, str]:
        """Generate the CTE for list aggregations using LATERAL FLATTEN."""
        cte_name = f"LIST_MERGED_FV{self._fv_index}"

        # Generate a more efficient single-pass CTE
        # Each list feature gets its own lateral flatten in the FROM clause
        cte_body = self._generate_list_cte_body()

        return cte_name, cte_body.strip()

    def _generate_secondary_key_merged_cte(self) -> tuple[str, str]:
        """Generate the CTE for secondary-key aggregations.

        Inner ``GROUP BY sk`` re-aggregates scalar partials per sk; outer
        ``ARRAY_AGG ... ORDER BY sk`` produces element-aligned keys/values
        arrays per ``(entity, boundary)``, one subquery per ``(window, offset)``.

        Returns:
            Tuple of (cte_name, cte_body) for the secondary key merged CTE.

        Raises:
            RuntimeError: Unsupported aggregation function (unreachable given
                upstream FV-level validation).
        """
        assert self._secondary_key is not None  # invariant: gated by caller
        cte_name = f"SECONDARY_KEY_MERGED_FV{self._fv_index}"
        secondary_key = self._secondary_key

        join_keys_list = list(self._join_keys)
        group_by_cols = join_keys_list + [_TILE_BOUNDARY_COL]
        group_by_str = ", ".join(group_by_cols)

        # Group value features by their synthesized keys-spec: one subquery
        # per (window, offset), emitting one keys column + N value-array
        # columns. The keys-column name comes directly from the keys-spec,
        # so the FV's column-naming convention lives in exactly one place
        # (``Feature._default_output_name``).
        keys_spec_by_window_offset: dict[tuple[str, str], AggregationSpec] = {
            (s.window, s.offset): s for s in self._keys_specs
        }

        features_by_window_offset: dict[tuple[str, str], list[AggregationSpec]] = {}
        for spec in self._secondary_key_features:
            group_key = (spec.window, spec.offset)
            features_by_window_offset.setdefault(group_key, []).append(spec)

        # (keys_col, value_output_cols, subquery_sql) per (window, offset) group
        subqueries: list[tuple[str, list[str], str]] = []

        for window_offset, specs in features_by_window_offset.items():
            # WHERE-filter on the inner query so sks with no events in this
            # window are absent from the keys array rather than showing as zero.
            tile_filter = self._get_tile_filter_condition(specs[0])

            inner_exprs: list[str] = []
            outer_exprs: list[str] = []
            value_output_cols: list[str] = []
            seen_output: set[str] = set()

            for spec in specs:
                output_col = spec.get_sql_column_name()
                if output_col in seen_output:
                    continue
                seen_output.add(output_col)
                value_output_cols.append(output_col)

                if spec.function == AggregationType.SUM:
                    partial = spec.get_tile_column_name("SUM")
                    inner_exprs.append(f"SUM({partial}) AS {output_col}")
                elif spec.function == AggregationType.COUNT:
                    partial = spec.get_tile_column_name("COUNT")
                    inner_exprs.append(f"SUM({partial}) AS {output_col}")
                elif spec.function == AggregationType.MIN:
                    partial = spec.get_tile_column_name("MIN")
                    inner_exprs.append(f"MIN({partial}) AS {output_col}")
                elif spec.function == AggregationType.MAX:
                    partial = spec.get_tile_column_name("MAX")
                    inner_exprs.append(f"MAX({partial}) AS {output_col}")
                elif spec.function == AggregationType.AVG:
                    sum_partial = spec.get_tile_column_name("SUM")
                    count_partial = spec.get_tile_column_name("COUNT")
                    inner_exprs.append(
                        f"CASE WHEN SUM({count_partial}) > 0 "
                        f"THEN SUM({sum_partial}) / SUM({count_partial}) "
                        f"ELSE NULL END AS {output_col}"
                    )
                elif spec.function in (AggregationType.STD, AggregationType.VAR):
                    # VAR = SUM(SUM_SQ)/SUM(COUNT) - (SUM(SUM)/SUM(COUNT))^2
                    # across tiles within (entity, sk). GREATEST(0, ...) clamps
                    # fp noise; mirrors the non-SK branch above.
                    sum_partial = spec.get_tile_column_name("SUM")
                    count_partial = spec.get_tile_column_name("COUNT")
                    sum_sq_partial = spec.get_tile_column_name("SUM_SQ")
                    variance_expr = (
                        f"SUM({sum_sq_partial}) / SUM({count_partial}) "
                        f"- POWER(SUM({sum_partial}) / SUM({count_partial}), 2)"
                    )
                    if spec.function == AggregationType.STD:
                        body = f"SQRT(GREATEST(0, {variance_expr}))"
                    else:
                        body = f"GREATEST(0, {variance_expr})"
                    inner_exprs.append(
                        f"CASE WHEN SUM({count_partial}) > 0 " f"THEN {body} " f"ELSE NULL END AS {output_col}"
                    )
                elif spec.function == AggregationType.APPROX_COUNT_DISTINCT:
                    # HLL states are mergeable across tiles per (entity, sk):
                    # combine the HLL_IMPORT'd states then estimate.
                    partial = spec.get_tile_column_name("HLL")
                    inner_exprs.append(f"HLL_ESTIMATE(HLL_COMBINE(HLL_IMPORT({partial}))) AS {output_col}")
                elif spec.function == AggregationType.APPROX_PERCENTILE:
                    # T-Digest states are likewise mergeable across tiles per
                    # (entity, sk): combine then estimate at the requested
                    # percentile.
                    partial = spec.get_tile_column_name("TDIGEST")
                    percentile = spec.params.get("percentile", 0.5)
                    inner_exprs.append(
                        f"APPROX_PERCENTILE_ESTIMATE(APPROX_PERCENTILE_COMBINE({partial}), {percentile}) "
                        f"AS {output_col}"
                    )
                else:
                    # Unreachable — FV-level validation restricts this set.
                    raise RuntimeError(
                        f"Unsupported aggregation function {spec.function} for secondary key feature "
                        f"'{spec.output_column}'."
                    )

                # ``ARRAY_AGG`` drops SQL NULLs; coerce to VARIANT JSON null
                # so all-NULL (entity, sk, window) groups still occupy a slot
                # and stay element-aligned with the keys array.
                outer_exprs.append(
                    f"ARRAY_AGG(NVL({output_col}, PARSE_JSON('null'))) "
                    f"WITHIN GROUP (ORDER BY {secondary_key}) AS {output_col}"
                )

            keys_output_col = keys_spec_by_window_offset[window_offset].get_sql_column_name()
            keys_agg = f"ARRAY_AGG({secondary_key}) WITHIN GROUP (ORDER BY {secondary_key}) AS {keys_output_col}"

            subquery = f"""
    (SELECT
         {group_by_str},
         {keys_agg},
         {', '.join(outer_exprs)}
     FROM (
         SELECT
             {group_by_str},
             {secondary_key},
             {', '.join(inner_exprs)}
         FROM TILES_JOINED_FV{self._fv_index}
         WHERE {tile_filter}
         GROUP BY {group_by_str}, {secondary_key}
     ) per_sk
     WHERE {secondary_key} IS NOT NULL
     GROUP BY {group_by_str}
    )"""

            subqueries.append((keys_output_col, value_output_cols, subquery))

        if len(subqueries) == 1:
            cte_body = subqueries[0][2].strip()
        else:
            # Multiple (sk, window) groups — LEFT JOIN on (entity_keys, boundary).
            _, _, first_query = subqueries[0]
            projected: list[str] = [f"sq0.{col}" for col in group_by_cols]
            projected.append(f"sq0.{subqueries[0][0]}")
            for col in subqueries[0][1]:
                projected.append(f"sq0.{col}")
            for i, (keys_col, value_cols, _) in enumerate(subqueries[1:], 1):
                projected.append(f"sq{i}.{keys_col}")
                for col in value_cols:
                    projected.append(f"sq{i}.{col}")

            result = f"SELECT {', '.join(projected)}\n    FROM {first_query} sq0"
            for i, (_, _, query) in enumerate(subqueries[1:], 1):
                join_cond = " AND ".join(f"sq0.{col} = sq{i}.{col}" for col in group_by_cols)
                result += f"\n    LEFT JOIN {query} sq{i}\n    ON {join_cond}"
            cte_body = result

        return cte_name, cte_body.strip()

    def _generate_lifetime_merged_cte(self) -> tuple[str, str]:
        """Generate the CTE for lifetime simple aggregations using ASOF JOIN.

        Uses ASOF JOIN on cumulative columns for O(1) lookup per boundary.
        This is much faster than aggregating all tiles from the beginning of time.

        Returns:
            Tuple of (cte_name, cte_body) for the lifetime merged CTE.
        """
        cte_name = f"LIFETIME_MERGED_FV{self._fv_index}"

        group_by_cols = list(self._join_keys) + [_TILE_BOUNDARY_COL]

        # Build ASOF JOIN condition: match the most recent tile before the boundary
        asof_match = f"UB.{_TILE_BOUNDARY_COL} > TILES.{_TILE_START_COL}"
        join_conditions = [f"UB.{k} = TILES.{k}" for k in self._join_keys]
        join_conditions_str = " AND ".join(join_conditions)

        # Build select columns for lifetime features
        select_cols = []
        for spec in self._lifetime_simple_features:
            output_col = spec.get_sql_column_name()

            if spec.function == AggregationType.SUM:
                cum_col = spec.get_cumulative_column_name("SUM")
                select_cols.append(f"TILES.{cum_col} AS {output_col}")

            elif spec.function == AggregationType.COUNT:
                cum_col = spec.get_cumulative_column_name("COUNT")
                select_cols.append(f"TILES.{cum_col} AS {output_col}")

            elif spec.function == AggregationType.AVG:
                cum_sum = spec.get_cumulative_column_name("SUM")
                cum_count = spec.get_cumulative_column_name("COUNT")
                select_cols.append(
                    f"CASE WHEN TILES.{cum_count} > 0 "
                    f"THEN TILES.{cum_sum} / TILES.{cum_count} "
                    f"ELSE NULL END AS {output_col}"
                )

            elif spec.function == AggregationType.MIN:
                cum_col = spec.get_cumulative_column_name("MIN")
                select_cols.append(f"TILES.{cum_col} AS {output_col}")

            elif spec.function == AggregationType.MAX:
                cum_col = spec.get_cumulative_column_name("MAX")
                select_cols.append(f"TILES.{cum_col} AS {output_col}")

            elif spec.function == AggregationType.VAR:
                cum_sum = spec.get_cumulative_column_name("SUM")
                cum_count = spec.get_cumulative_column_name("COUNT")
                cum_sum_sq = spec.get_cumulative_column_name("SUM_SQ")
                select_cols.append(
                    f"CASE WHEN TILES.{cum_count} > 0 "
                    f"THEN GREATEST(0, "
                    f"TILES.{cum_sum_sq} / TILES.{cum_count} "
                    f"- POWER(TILES.{cum_sum} / TILES.{cum_count}, 2)) "
                    f"ELSE NULL END AS {output_col}"
                )

            elif spec.function == AggregationType.STD:
                cum_sum = spec.get_cumulative_column_name("SUM")
                cum_count = spec.get_cumulative_column_name("COUNT")
                cum_sum_sq = spec.get_cumulative_column_name("SUM_SQ")
                select_cols.append(
                    f"CASE WHEN TILES.{cum_count} > 0 "
                    f"THEN SQRT(GREATEST(0, "
                    f"TILES.{cum_sum_sq} / TILES.{cum_count} "
                    f"- POWER(TILES.{cum_sum} / TILES.{cum_count}, 2))) "
                    f"ELSE NULL END AS {output_col}"
                )

            elif spec.function == AggregationType.APPROX_COUNT_DISTINCT:
                cum_col = spec.get_cumulative_column_name("HLL")
                select_cols.append(f"HLL_ESTIMATE(HLL_IMPORT(TILES.{cum_col})) AS {output_col}")

            elif spec.function == AggregationType.APPROX_PERCENTILE:
                cum_col = spec.get_cumulative_column_name("TDIGEST")
                percentile = spec.params.get("percentile", 0.5)
                select_cols.append(f"APPROX_PERCENTILE_ESTIMATE(TILES.{cum_col}, {percentile}) AS {output_col}")

        select_cols_str = ", ".join(select_cols)

        # Qualify group by columns with UB alias to avoid ambiguity in ASOF JOIN
        qualified_group_cols = [f"UB.{col}" for col in group_by_cols]
        qualified_group_str = ", ".join(qualified_group_cols)

        cte_body = f"""
    SELECT
        {qualified_group_str},
        {select_cols_str}
    FROM UNIQUE_BOUNDS_FV{self._fv_index} UB
    ASOF JOIN {self._tile_table} TILES
      MATCH_CONDITION ({asof_match})
      ON {join_conditions_str}
"""
        return cte_name, cte_body.strip()

    def _generate_list_cte_body(self) -> str:
        """Generate the body of the list merged CTE.

        Groups by entity keys + TILE_BOUNDARY (not spine timestamp) for efficiency.

        Returns:
            SQL string for the list merged CTE body.
        """
        # Group by entity keys + TILE_BOUNDARY (optimization)
        group_by_cols = list(self._join_keys) + [_TILE_BOUNDARY_COL]
        group_by_str = ", ".join(group_by_cols)
        select_group_cols = ", ".join(f"t.{col}" for col in group_by_cols)

        if not self._list_features:
            return f"SELECT {group_by_str} FROM TILES_JOINED_FV{self._fv_index} WHERE 1=0"

        # Build subqueries for each list feature
        feature_subqueries = []

        for _idx, spec in enumerate(self._list_features):
            # Determine the tile column name based on aggregation type
            if spec.function in (AggregationType.LAST_N, AggregationType.LAST_DISTINCT_N):
                col_name = spec.get_tile_column_name("LAST")
                order_clause = f"t.{_TILE_START_COL} DESC, flat.INDEX ASC"
            else:  # FIRST_N, FIRST_DISTINCT_N
                col_name = spec.get_tile_column_name("FIRST")
                order_clause = f"t.{_TILE_START_COL} ASC, flat.INDEX ASC"

            output_col = spec.get_sql_column_name()
            n_value = spec.params["n"]

            # Calculate tile filter condition for window and offset
            tile_filter = self._get_list_tile_filter_condition(spec)

            is_distinct = spec.function in (AggregationType.LAST_DISTINCT_N, AggregationType.FIRST_DISTINCT_N)

            if is_distinct:
                # For distinct, use QUALIFY to keep first occurrence of each value
                # Note: Inner query uses t. prefix, outer query uses bare column names
                subquery = f"""
    (SELECT {group_by_str},
            ARRAY_AGG(val) WITHIN GROUP (ORDER BY rn) AS {output_col}
     FROM (
         SELECT {select_group_cols}, flat.VALUE AS val,
                ROW_NUMBER() OVER (PARTITION BY {select_group_cols} ORDER BY {order_clause}) AS rn,
                ROW_NUMBER() OVER (PARTITION BY {select_group_cols}, flat.VALUE ORDER BY {order_clause}) AS dup_rn
         FROM TILES_JOINED_FV{self._fv_index} t,
         LATERAL FLATTEN(INPUT => t.{col_name}) flat
         WHERE {tile_filter}
         AND flat.VALUE IS NOT NULL
     ) ranked
     WHERE dup_rn = 1 AND rn <= {n_value}
     GROUP BY {group_by_str}
    )"""
            else:
                # Non-distinct: straightforward flatten and aggregate
                subquery = f"""
    (SELECT {select_group_cols},
            ARRAY_SLICE(
                ARRAY_AGG(flat.VALUE) WITHIN GROUP (ORDER BY {order_clause}),
                0, {n_value}
            ) AS {output_col}
     FROM TILES_JOINED_FV{self._fv_index} t,
     LATERAL FLATTEN(INPUT => t.{col_name}) flat
     WHERE {tile_filter}
     AND flat.VALUE IS NOT NULL
     GROUP BY {select_group_cols}
    )"""

            feature_subqueries.append((output_col, subquery))

        # Combine all subqueries with JOINs
        if len(feature_subqueries) == 1:
            return feature_subqueries[0][1]

        # Multiple list features: join them together
        first_name, first_query = feature_subqueries[0]
        result = "SELECT sq0.*, "
        for i, (name, _) in enumerate(feature_subqueries[1:], 1):
            result += f"sq{i}.{name}"
            if i < len(feature_subqueries) - 1:
                result += ", "

        result += f"\n    FROM {first_query} sq0"

        for i, (_name, query) in enumerate(feature_subqueries[1:], 1):
            join_cond = " AND ".join(f"sq0.{col} = sq{i}.{col}" for col in group_by_cols)
            result += f"\n    LEFT JOIN {query} sq{i}\n    ON {join_cond}"

        return result

    def _generate_combined_cte(self) -> tuple[str, str]:
        """Generate the final CTE that combines and expands results.

        This joins the merged results (grouped by entity + TILE_BOUNDARY) back to
        the original spine (SPINE_BOUNDARY) to expand to per-spine-row output.

        Returns:
            Tuple of (cte_name, cte_body) for the combined CTE.
        """
        cte_name = f"FV{self._fv_index:03d}"

        spine_output_cols = list(self._join_keys) + [self._spine_timestamp_col]
        # Merged results are grouped by entity + TILE_BOUNDARY
        boundary_group_cols = list(self._join_keys) + [_TILE_BOUNDARY_COL]

        # Select columns from spine (entity keys + original timestamp)
        select_cols = [f"s.{col}" for col in spine_output_cols]

        # Add simple feature columns (non-lifetime)
        for spec in self._simple_features:
            select_cols.append(f"simple.{spec.get_sql_column_name()}")

        # Add list feature columns (non-lifetime)
        for spec in self._list_features:
            select_cols.append(f"list_agg.{spec.get_sql_column_name()}")

        # Add secondary key columns: one COALESCE-wrapped array per non-lifetime spec
        # (covers both synthesized keys-specs and value-array specs).
        if self._secondary_key_features:
            for spec in self._features:
                if spec.is_lifetime():
                    continue
                col = spec.get_sql_column_name()
                select_cols.append(f"COALESCE(secondary_key.{col}, ARRAY_CONSTRUCT()) AS {col}")

        # Add lifetime simple feature columns
        for spec in self._lifetime_simple_features:
            select_cols.append(f"lifetime.{spec.get_sql_column_name()}")

        # Build FROM clause with all necessary JOINs
        from_clause = f"SPINE_BOUNDARY_FV{self._fv_index} s"
        joins = []

        # Join condition template
        def make_join_cond(alias: str) -> str:
            return " AND ".join(f"s.{col} = {alias}.{col}" for col in boundary_group_cols)

        # Add JOINs for each CTE that has features
        if self._simple_features:
            joins.append(f"LEFT JOIN SIMPLE_MERGED_FV{self._fv_index} simple ON {make_join_cond('simple')}")

        if self._list_features:
            joins.append(f"LEFT JOIN LIST_MERGED_FV{self._fv_index} list_agg ON {make_join_cond('list_agg')}")

        if self._secondary_key_features:
            joins.append(
                f"LEFT JOIN SECONDARY_KEY_MERGED_FV{self._fv_index} secondary_key ON {make_join_cond('secondary_key')}"
            )

        if self._lifetime_simple_features:
            joins.append(f"LEFT JOIN LIFETIME_MERGED_FV{self._fv_index} lifetime ON {make_join_cond('lifetime')}")

        if joins:
            cte_body = f"""
    SELECT {', '.join(select_cols)}
    FROM {from_clause}
    {chr(10).join('    ' + j for j in joins)}
"""
        else:
            # No features (shouldn't happen)
            cte_body = f"""
    SELECT DISTINCT {', '.join(spine_output_cols)}
    FROM SPINE
"""

        return cte_name, cte_body.strip()

    def get_output_columns(self) -> list[str]:
        """Get the list of output column names from this feature view."""
        return [spec.output_column for spec in self._features]


class RollupSqlGenerator:
    """Generates SQL for rolling up tiles to a coarser entity level.

    Uses the same aggregation logic as tile merging - the mathematical
    operations are identical, just applied across entities instead of time.

    Example:
        parent_tile_table: "DB.SCHEMA.VISITOR_FV$V1"
        parent_join_keys: ["visitor_id", "company_id"]
        new_join_keys: ["subscriber_id", "company_id"]
        mapping_query: "SELECT * FROM visitor_subscriber_mapping"

        Generated SQL:
            SELECT
                m.subscriber_id,
                t.company_id,  -- shared key comes from tile table
                t.TILE_START,
                SUM(t._PARTIAL_COUNT_VISITOR_ID) AS _PARTIAL_COUNT_VISITOR_ID,
                ...
            FROM DB.SCHEMA.VISITOR_FV$V1 t
            JOIN (SELECT * FROM visitor_subscriber_mapping) m
                ON t.visitor_id = m.visitor_id AND t.company_id = m.company_id
            WHERE m.subscriber_id IS NOT NULL
            GROUP BY m.subscriber_id, t.company_id, t.TILE_START
    """

    def __init__(
        self,
        parent_tile_table: str,
        parent_join_keys: list[str],
        new_join_keys: list[str],
        mapping_query: str,
        aggregation_specs: list[AggregationSpec],
        mapping_valid_from_col: Optional[str] = None,
        mapping_valid_to_col: Optional[str] = None,
    ) -> None:
        """Initialize the rollup SQL generator.

        Args:
            parent_tile_table: Fully qualified name of the parent tile table.
            parent_join_keys: Join keys from the parent entity.
            new_join_keys: Join keys for the new (rolled up) entity.
            mapping_query: SQL query that returns the mapping table.
            aggregation_specs: Aggregation specifications from the parent FV.
            mapping_valid_from_col: When provided together with mapping_valid_to_col,
                uses a range JOIN instead of a plain JOIN for point-in-time correct
                entity resolution with bounded validity windows [valid_from, valid_to).
                Supports 1:N mappings (one child entity to multiple parent entities).
            mapping_valid_to_col: Must be provided together with mapping_valid_from_col.
                Timestamp column indicating when each mapping expired. NULL values
                are treated as still-active.
        """
        self._parent_tile_table = parent_tile_table
        self._parent_join_keys = [k.upper() for k in parent_join_keys]
        self._new_join_keys = [k.upper() for k in new_join_keys]
        self._mapping_query = mapping_query
        self._aggregation_specs = aggregation_specs
        self._mapping_valid_from_col = (
            SqlIdentifier(mapping_valid_from_col).identifier() if mapping_valid_from_col else None
        )
        self._mapping_valid_to_col = SqlIdentifier(mapping_valid_to_col).identifier() if mapping_valid_to_col else None

        self._lifetime_specs = [s for s in aggregation_specs if s.is_lifetime()]
        self._has_lifetime_features = bool(self._lifetime_specs)

    def generate(self) -> str:
        """Generate the rollup SQL query.

        Routes to the appropriate implementation based on whether list
        features (LAST_N, FIRST_N, etc.) are present. List features require
        a CTE-based approach with LATERAL FLATTEN to preserve global
        timestamp ordering across child entities.

        Returns:
            SQL query string for creating the rollup Dynamic Table.
        """
        has_list_features = any(s.function.is_list() for s in self._aggregation_specs)

        if not has_list_features:
            return self._generate_simple_rollup()
        else:
            return self._generate_rollup_with_lists()

    def generate_as_cte(self, cte_name: str) -> tuple[str, str]:
        """Generate the rollup SQL as a CTE (name, body) tuple.

        Used at training time to inject a PIT-correct rollup CTE into the
        MergingSqlGenerator CTE chain.

        Args:
            cte_name: Name for the CTE (e.g., "PIT_ROLLUP_FV0").

        Returns:
            Tuple of (cte_name, cte_body) that can be prepended to a CTE chain.
        """
        body = self.generate().strip()
        if body.endswith(";"):
            body = body[:-1].strip()
        return (cte_name, body)

    def _get_not_null_expr(self) -> str:
        """Get the WHERE NOT NULL filter expression for the mapping join.

        Returns:
            SQL expression like "m.subscriber_id IS NOT NULL".
        """
        not_null_key = None
        for key in self._new_join_keys:
            if key not in self._parent_join_keys:
                not_null_key = key
                break
        if not_null_key is None:
            not_null_key = self._new_join_keys[0]

        if not_null_key in self._parent_join_keys:
            return f"t.{not_null_key} IS NOT NULL"
        else:
            return f"m.{not_null_key} IS NOT NULL"

    def _build_join_clause(self) -> str:
        """Build the JOIN clause between tile table and mapping table.

        Two paths:
        - Neither temporal column set: plain JOIN (non-temporal rollup).
        - Both ``valid_from`` and ``valid_to`` set: range JOIN with bounded
          validity window ``[valid_from, valid_to)``, supporting 1:N mappings
          where one child entity maps to multiple parent entities simultaneously.

        Returns:
            SQL JOIN clause string.
        """
        join_conditions = [f"t.{key} = m.{key}" for key in self._parent_join_keys]

        if self._mapping_valid_from_col is not None:
            range_conditions = join_conditions + [
                f"t.{_TILE_START_COL} >= m.{self._mapping_valid_from_col}",
                f"(m.{self._mapping_valid_to_col} IS NULL" f" OR t.{_TILE_START_COL} < m.{self._mapping_valid_to_col})",
            ]
            return f"JOIN ({self._mapping_query}) m\n    ON {' AND '.join(range_conditions)}"
        else:
            return f"JOIN ({self._mapping_query}) m\n    ON {' AND '.join(join_conditions)}"

    def _wrap_with_cumulative(self, inner_sql: str) -> str:
        """Wrap a rollup query with cumulative window functions for lifetime features.

        When the parent FV has lifetime aggregation specs, the rollup output
        needs ``_CUM_*`` columns (running aggregates partitioned by the rolled-up
        entity keys) so that ``MergingSqlGenerator.LIFETIME_MERGED`` can read
        them via ASOF JOIN.

        Args:
            inner_sql: The rollup SQL producing ``_PARTIAL_*`` columns.

        Returns:
            SQL with an outer SELECT adding ``_CUM_*`` columns, or the original
            SQL unchanged if there are no lifetime features.
        """
        if not self._has_lifetime_features:
            return inner_sql

        cum_exprs = _generate_cumulative_expressions(self._lifetime_specs, self._new_join_keys)
        if not cum_exprs:
            return inner_sql

        inner = inner_sql.strip()
        if inner.endswith(";"):
            inner = inner[:-1].strip()

        return f"""
SELECT
    base.*,
    {', '.join(cum_exprs)}
FROM (
{inner}
) base
"""

    def _generate_simple_rollup(self) -> str:
        """Generate rollup SQL when there are no list features.

        Uses a single SELECT...GROUP BY query. This is the original approach
        and is correct for simple aggregations (SUM, COUNT, AVG, etc.).

        Returns:
            SQL query string.
        """
        select_cols = []
        seen_columns: set[str] = set()

        # New entity keys - prefer from tile table if shared, else from mapping
        for key in self._new_join_keys:
            if key in self._parent_join_keys:
                select_cols.append(f"t.{key}")
            else:
                select_cols.append(f"m.{key}")

        # TILE_START
        select_cols.append(f"t.{_TILE_START_COL}")

        # Aggregation columns (with deduplication)
        for spec in self._aggregation_specs:
            for col_expr in self._get_rollup_aggs(spec, table_prefix="t"):
                # Extract column name from "... AS col_name"
                col_name = col_expr.split(" AS ")[-1].strip()
                if col_name not in seen_columns:
                    select_cols.append(col_expr)
                    seen_columns.add(col_name)

        # GROUP BY (new entity keys + TILE_START)
        group_by_cols = []
        for key in self._new_join_keys:
            if key in self._parent_join_keys:
                group_by_cols.append(f"t.{key}")
            else:
                group_by_cols.append(f"m.{key}")
        group_by_cols.append(f"t.{_TILE_START_COL}")

        not_null_expr = self._get_not_null_expr()
        join_clause = self._build_join_clause()

        inner = f"""
SELECT
    {', '.join(select_cols)}
FROM {self._parent_tile_table} t
{join_clause}
WHERE {not_null_expr}
GROUP BY {', '.join(group_by_cols)}
"""
        return self._wrap_with_cumulative(inner)

    def _generate_rollup_with_lists(self) -> str:
        """Generate rollup SQL with proper timestamp ordering for list features.

        Uses a CTE-based approach:
        1. base: Join tiles with mapping (no GROUP BY), exposing all tile columns
        2. simple_rollup: GROUP BY for simple/sketch features (if any)
        3. list_rollup_N: LATERAL FLATTEN + ARRAY_AGG ORDER BY timestamp for each
           unique list column pair (value array + companion TS array)
        4. Final SELECT joining all parts

        The LATERAL FLATTEN decomposes per-visitor arrays into individual rows,
        and the ARRAY_AGG with ORDER BY on the companion timestamp column
        re-aggregates them in correct global timestamp order.

        Returns:
            SQL query string.
        """
        simple_specs = [s for s in self._aggregation_specs if not s.function.is_list()]
        list_specs = [s for s in self._aggregation_specs if s.function.is_list()]

        # Entity key expressions (qualified for the base CTE)
        entity_select = []
        for key in self._new_join_keys:
            if key in self._parent_join_keys:
                entity_select.append(f"t.{key}")
            else:
                entity_select.append(f"m.{key}")
        entity_keys = list(self._new_join_keys)

        not_null_expr = self._get_not_null_expr()
        join_clause = self._build_join_clause()

        # Collect all tile columns needed (with dedup)
        all_tile_cols: set[str] = set()
        for spec in self._aggregation_specs:
            for col in self._get_tile_columns_for_spec(spec):
                all_tile_cols.add(col)
        tile_cols_sorted = sorted(all_tile_cols)

        # Group key for subsequent CTEs (unqualified column names)
        group_key_cols = entity_keys + [_TILE_START_COL]
        group_key_str = ", ".join(group_key_cols)

        ctes = []

        # --- CTE: base ---
        base_select = entity_select + [f"t.{_TILE_START_COL}"] + [f"t.{c}" for c in tile_cols_sorted]
        ctes.append(
            f"""base AS (
    SELECT
        {', '.join(base_select)}
    FROM {self._parent_tile_table} t
    {join_clause}
    WHERE {not_null_expr}
)"""
        )

        # --- CTE: simple_rollup (if any simple/sketch features) ---
        has_simple = bool(simple_specs)
        if has_simple:
            simple_agg_exprs: list[str] = []
            seen: set[str] = set()
            for spec in simple_specs:
                for expr in self._get_rollup_aggs(spec, table_prefix=""):
                    col_name = expr.split(" AS ")[-1].strip()
                    if col_name not in seen:
                        simple_agg_exprs.append(expr)
                        seen.add(col_name)

            ctes.append(
                f"""simple_rollup AS (
    SELECT
        {group_key_str},
        {', '.join(simple_agg_exprs)}
    FROM base
    GROUP BY {group_key_str}
)"""
            )

        # --- CTEs: list_rollup_N for each unique list column pair ---
        # Each unique (val_col, ts_col) gets its own LATERAL FLATTEN CTE.
        # Multiple specs may share the same tile column (e.g., LAST_N and
        # LAST_DISTINCT_N on the same source column) — dedup by val_col.
        list_rollup_info: list[tuple[str, str, str]] = []  # (cte_name, val_col, ts_col)
        seen_list_cols: set[str] = set()

        for spec in list_specs:
            if spec.function in (AggregationType.LAST_N, AggregationType.LAST_DISTINCT_N):
                val_col = spec.get_tile_column_name("LAST")
                ts_col = spec.get_tile_column_name("LAST_TS")
                order = "DESC"
            else:  # FIRST_N, FIRST_DISTINCT_N
                val_col = spec.get_tile_column_name("FIRST")
                ts_col = spec.get_tile_column_name("FIRST_TS")
                order = "ASC"

            if val_col in seen_list_cols:
                continue
            seen_list_cols.add(val_col)

            idx = len(list_rollup_info)
            cte_name = f"list_rollup_{idx}"
            list_rollup_info.append((cte_name, val_col, ts_col))

            ctes.append(
                f"""{cte_name} AS (
    SELECT
        {group_key_str},
        ARRAY_AGG(flat.VALUE) WITHIN GROUP (
            ORDER BY {ts_col}[flat.INDEX] {order}
        ) AS {val_col},
        ARRAY_AGG({ts_col}[flat.INDEX]) WITHIN GROUP (
            ORDER BY {ts_col}[flat.INDEX] {order}
        ) AS {ts_col}
    FROM base,
    LATERAL FLATTEN(INPUT => {val_col}) flat
    WHERE flat.VALUE IS NOT NULL
    GROUP BY {group_key_str}
)"""
            )

        # --- Final SELECT: join simple_rollup with list_rollup CTEs ---
        final_select_cols: list[str] = []

        if has_simple:
            # Entity keys + TILE_START from simple_rollup
            for key in group_key_cols:
                final_select_cols.append(f"s.{key}")
            # Simple aggregation columns
            seen_final: set[str] = set()
            for spec in simple_specs:
                for expr in self._get_rollup_aggs(spec, table_prefix=""):
                    col_name = expr.split(" AS ")[-1].strip()
                    if col_name not in seen_final:
                        final_select_cols.append(f"s.{col_name}")
                        seen_final.add(col_name)
        else:
            # Entity keys + TILE_START from first list rollup
            for key in group_key_cols:
                final_select_cols.append(f"l0.{key}")

        # List columns from list_rollup CTEs
        for i, (_cte_name, val_col, ts_col) in enumerate(list_rollup_info):
            alias = f"l{i}"
            final_select_cols.append(f"{alias}.{val_col}")
            final_select_cols.append(f"{alias}.{ts_col}")

        # Build FROM clause with JOINs
        if has_simple:
            from_clause = "simple_rollup s"
            for i, (cte_name, _val, _ts) in enumerate(list_rollup_info):
                alias = f"l{i}"
                join_cond = " AND ".join(f"s.{k} = {alias}.{k}" for k in group_key_cols)
                from_clause += f"\n    LEFT JOIN {cte_name} {alias} ON {join_cond}"
        else:
            # No simple features - use first list rollup as primary
            first_name = list_rollup_info[0][0]
            from_clause = f"{first_name} l0"
            for i, (cte_name, _val, _ts) in enumerate(list_rollup_info[1:], 1):
                alias = f"l{i}"
                join_cond = " AND ".join(f"l0.{k} = {alias}.{k}" for k in group_key_cols)
                from_clause += f"\n    LEFT JOIN {cte_name} {alias} ON {join_cond}"

        cte_str = ",\n".join(ctes)

        inner = f"""
WITH {cte_str}
SELECT
    {', '.join(final_select_cols)}
FROM {from_clause}
"""
        return self._wrap_with_cumulative(inner)

    def _get_tile_columns_for_spec(self, spec: AggregationSpec) -> list[str]:
        """Get all tile column names needed for a given aggregation spec.

        This is used to build the base CTE SELECT list in the CTE-based
        rollup approach.

        Args:
            spec: The aggregation specification.

        Returns:
            List of tile column names needed by this spec.
        """
        if spec.function == AggregationType.COUNT:
            return [spec.get_tile_column_name("COUNT")]
        elif spec.function == AggregationType.SUM:
            return [spec.get_tile_column_name("SUM")]
        elif spec.function == AggregationType.AVG:
            return [spec.get_tile_column_name("SUM"), spec.get_tile_column_name("COUNT")]
        elif spec.function == AggregationType.MIN:
            return [spec.get_tile_column_name("MIN")]
        elif spec.function == AggregationType.MAX:
            return [spec.get_tile_column_name("MAX")]
        elif spec.function in (AggregationType.STD, AggregationType.VAR):
            return [
                spec.get_tile_column_name("SUM"),
                spec.get_tile_column_name("COUNT"),
                spec.get_tile_column_name("SUM_SQ"),
            ]
        elif spec.function == AggregationType.APPROX_COUNT_DISTINCT:
            return [spec.get_tile_column_name("HLL")]
        elif spec.function == AggregationType.APPROX_PERCENTILE:
            return [spec.get_tile_column_name("TDIGEST")]
        elif spec.function in (AggregationType.LAST_N, AggregationType.LAST_DISTINCT_N):
            return [spec.get_tile_column_name("LAST"), spec.get_tile_column_name("LAST_TS")]
        elif spec.function in (AggregationType.FIRST_N, AggregationType.FIRST_DISTINCT_N):
            return [spec.get_tile_column_name("FIRST"), spec.get_tile_column_name("FIRST_TS")]
        return []

    def _get_rollup_aggs(self, spec: AggregationSpec, table_prefix: str = "t") -> list[str]:
        """Get rollup aggregation expressions for a spec.

        These are the same mathematical operations used for tile merging,
        just applied across entities instead of time.

        Note: List features (LAST_N, FIRST_N, etc.) are NOT handled here —
        they use a separate CTE-based approach with LATERAL FLATTEN. This
        method only handles simple and sketch aggregations.

        Args:
            spec: The aggregation specification.
            table_prefix: Table alias prefix for column references.
                Use "t" for direct table queries, "" for CTE-based queries.

        Returns:
            List of SQL expressions for this aggregation's rollup.
        """
        results = []
        p = f"{table_prefix}." if table_prefix else ""

        if spec.function == AggregationType.COUNT:
            col = spec.get_tile_column_name("COUNT")
            results.append(f"SUM({p}{col}) AS {col}")

        elif spec.function == AggregationType.SUM:
            col = spec.get_tile_column_name("SUM")
            results.append(f"SUM({p}{col}) AS {col}")

        elif spec.function == AggregationType.AVG:
            sum_col = spec.get_tile_column_name("SUM")
            count_col = spec.get_tile_column_name("COUNT")
            results.append(f"SUM({p}{sum_col}) AS {sum_col}")
            results.append(f"SUM({p}{count_col}) AS {count_col}")

        elif spec.function == AggregationType.MIN:
            col = spec.get_tile_column_name("MIN")
            results.append(f"MIN({p}{col}) AS {col}")

        elif spec.function == AggregationType.MAX:
            col = spec.get_tile_column_name("MAX")
            results.append(f"MAX({p}{col}) AS {col}")

        elif spec.function in (AggregationType.STD, AggregationType.VAR):
            sum_col = spec.get_tile_column_name("SUM")
            count_col = spec.get_tile_column_name("COUNT")
            sum_sq_col = spec.get_tile_column_name("SUM_SQ")
            results.append(f"SUM({p}{sum_col}) AS {sum_col}")
            results.append(f"SUM({p}{count_col}) AS {count_col}")
            results.append(f"SUM({p}{sum_sq_col}) AS {sum_sq_col}")

        elif spec.function == AggregationType.APPROX_COUNT_DISTINCT:
            col = spec.get_tile_column_name("HLL")
            results.append(f"HLL_EXPORT(HLL_COMBINE(HLL_IMPORT({p}{col}))) AS {col}")

        elif spec.function == AggregationType.APPROX_PERCENTILE:
            col = spec.get_tile_column_name("TDIGEST")
            results.append(f"APPROX_PERCENTILE_COMBINE({p}{col}) AS {col}")

        # Note: LAST_N, FIRST_N, etc. are handled via LATERAL FLATTEN in
        # _generate_rollup_with_lists(), not here.

        return results
