import sys

from ruamel.yaml import YAML

from bazel import conda_env_utils

if __name__ == "__main__":

    if len(sys.argv) <= 1:
        raise ValueError("Must provide at least one conda env file.")

    yaml = YAML()
    conda_env = yaml.load(open(sys.argv[1]))
    _, deps = conda_env_utils.validate_and_get_conda_env(conda_env)
    sys.stdout.writelines(
        [
            "# DO NOT EDIT!\n",
            "# Generated by //bazel:generate_requirements\n",
            "# To update, run:\n",
            "# bazel build //bazel:requirements.txt && cp bazel-bin/bazel/requirements.txt .\n",
            "\n",
        ]
    )
    sys.stdout.writelines("\n".join(deps))
    sys.stdout.writelines("\n")
