---
- id: check-py-test-feature-tags
  name: Check py_test feature area tags
  description: Ensure all py_test targets have feature area tags
  entry: python bazel/check_feature_tags.py --precommit
  language: system
  files: BUILD\.bazel$
  stages:
    - commit
