---
# Add requirements information here and use `bazel run --config=pre_build //bazel/requirements:sync_requirements`
# to generate all other requirements files.
# Please provide the following fields when adding a new record:
# # Package Name Fields

# `name`: The name of the package. Set this if the package is available with the same name and is required in both `PyPI`
# and `conda`.

# `name_pypi`: The name of the package in `PyPI`. Set this only to indicate that it is available in `PyPI` only. You can
# also set this along with `name_conda` if the package has different names in `PyPI` and `conda`.

# `name_conda`: The name of the package in `conda`. Set this only to indicate that it is available in `conda` only. You
# can also set this along with `name_pypi` if the package has different names in `PyPI` and `conda`.

# (At least one of these three fields should be set.)

# # Development Version Fields

# `dev_version`: The version of the package to be pinned in the dev environment. Set this if the package is available
# with the same version and is required in both `PyPI` and conda.

# `dev_version_pypi`: The version from `PyPI` to be pinned in the dev environment. Set this only to indicate that it is
# available in `PyPI` only. You can also set this along with `dev_version_conda` if the package has different versions in
# `PyPI` and `conda`.

# `dev_version_conda`: The version from `conda` to be pinned in the dev environment. Set this only to indicate that it is
# available in `conda` only. You can also set this along with `dev_version_pypi` if the package has different versions in
# `PyPI` and `conda`.

# (At least one of these three fields should be set.)

# `require_gpu`: Set this to true if the package is only a requirement for the environment with GPUs.

# # Snowflake Anaconda Channel

# `from_channel`: Set this if the package is not available in the Snowflake Anaconda Channel
# (https://repo.anaconda.com/pkgs/snowflake).

# # Version Requirements Fields (for `snowflake-ml-python` release)

# `version_requirements`: The version requirements specifiers when this requirement is a dependency of the
# `snowflake-ml-python` release. Set this if the package is available with the same name and required in both `PyPI` and
# `conda`.

# `version_requirements_pypi`: The version requirements specifiers when this requirement is a dependency of the
#`snowflake-ml-python` release via `PyPI`. Set this only to indicate that it is required by the `PyPI` release only. You
# can also set this along with `version_requirements_conda` if the package has different versions in `PyPI` and `conda`.

# `version_requirements_conda`: The version requirements specifiers when this requirement is a dependency of the
# `snowflake-ml-python` release via `conda`. Set this only to indicate that it is required by the `conda` release only.
# You can also set this along with `version_requirements_pypi` if the package has different versions in `PyPI` and `conda`.

# (At least one of these three fields must be set to indicate that this package is a dependency of the release. If you
# don't want to constrain the version, set the field to an empty string.)

# # Extras Tags and Tags

# `requirements_extra_tags`: Set this to indicate that the package is an extras dependency of `snowflake-ml-python`.
# This requirement will be added to all extras tags specified here, and an `all` extras tag will be auto-generated to include
# all extras requirements. All extras requirements will be labeled as `run_constrained` in conda's meta.yaml.

# `tags`: Set tags to filter some of the requirements in specific cases. The current valid tags include:
#   - `build_essential`: Used to indicate the packages composing the build environment.
#   - `build_test_env`: Used to indicate the package is required in build and test environment to run the tests.

- name: absl-py
  dev_version: 1.4.0
  tags:
    - build_essential
    - build_test_env
# For fsspec[http] in conda
- name_conda: aiohttp
  dev_version_conda: 3.9.5
  version_requirements_conda: '!=4.0.0a0, !=4.0.0a1'
- name: anyio
  dev_version: 4.2.0
  version_requirements: '>=3.5.0,<5'
- name_conda: python-build
  name_pypi: build
  dev_version: 0.10.0
  tags:
    - build_essential
- name: boto3
  dev_version: 1.34.69
- name: catboost
  dev_version: 1.2.8
  version_requirements: '>=1.2.0, <2'
  requirements_extra_tags:
    - catboost
- name: cloudpickle
  dev_version: 2.2.1
  version_requirements: '>=2.0.0'
- name: cryptography
  dev_version: 41.0.3
  version_requirements: ''
  # Skipping version requirements as it should come as part of connector.
  # Only used in connection_params.py, which is an util library anyways.
- name: coverage
  dev_version: 7.6.1
- name: flask-cors
  dev_version: 3.0.10
- name: flask
  dev_version: 2.2.2
- name_pypi: fsspec[http]
  name_conda: fsspec
  dev_version: 2024.6.1
  version_requirements: '>=2024.6.1,<2026'
- name: httpx
  dev_version: 0.28.1
- name: importlib_resources
  dev_version: 6.1.1
  version_requirements: '>=6.1.1, <7'
- name: inflection
  dev_version: 0.5.1
  tags:
    - build_essential
    - build_test_env
- name: jsonschema
  dev_version: 4.23.0
  tags:
    - build_essential
- name: joblib
  dev_version: 1.4.2
- name: lightgbm
  dev_version: 4.1.0
  version_requirements: '>=4.1.0, <5'
  requirements_extra_tags:
    - lightgbm
  tags:
    - build_essential
- name: shap
  dev_version: 0.46.0
  version_requirements: '>=0.46.0,<1'
- name: mlflow
  dev_version: 2.16.2
  version_requirements: '>=2.16.0, <3'
  requirements_extra_tags:
    - mlflow
    - llm
- name: moto
  dev_version: 5.0.5
- name: mypy
  dev_version: 1.10.0
- name: networkx
  dev_version: 3.1
- name: numpy
  dev_version: 1.26.4
  version_requirements: '>=1.23,<3'
  tags:
    - build_essential
- name: packaging
  dev_version: '24.1'
  version_requirements: '>=20.9,<26'
  tags:
    - build_essential
- name: pandas
  dev_version: 2.1.4
  version_requirements: '>=2.1.4,<3'
- name: protobuf
  dev_version: 4.25.3
- name: prophet
  dev_version: 1.1.5
  version_requirements: '>=1.1.0, <2'
  requirements_extra_tags:
    - prophet
- name: psutil
  dev_version: 5.9.0
  tags:
    - build_test_env
- name: pyarrow
  dev_version: 16.1.0
  # pyarrow 19.0.0 is broken https://github.com/apache/arrow/issues/45283.
  # Setting the restriction to <19.0.0 because Snowpark doesn't support != and
  # v19.0.1 is not available in Snowflake conda channel yet.
  version_requirements: <19.0.0
- name: pydantic
  dev_version: 2.8.2
  version_requirements: '>=2.8.2, <3'
- name: pyjwt
  dev_version: 2.8.0
  version_requirements: '>=2.0.0, <3'
- name: pytest
  dev_version: 7.4.0
  tags:
    - build_test_env
- name: pytest-timeout
  dev_version: 2.2.0
  tags:
    - build_test_env
- name: pytest-xdist
  dev_version: 3.5.0
  tags:
    - build_test_env
- name_pypi: torch
  name_conda: pytorch
  dev_version: 2.5.1
  version_requirements: '>=2.0.1,<3'
  requirements_extra_tags:
    - torch
    - transformers
    - keras
    - llm
- name: pyyaml
  dev_version: 6.0.1
  version_requirements: '>=6.0,<7'
- name: retrying
  dev_version: 1.3.3
  version_requirements: '>=1.3.3,<2'
# For fsspec[http] in conda
- name_conda: requests
  dev_version_conda: 2.31.0
  version_requirements_conda: ''
- name: ruamel.yaml
  dev_version: 0.17.21
  tags:
    - build_essential
- name: s3fs
  dev_version: 2024.6.1
  version_requirements: '>=2024.6.1,<2026'
- name: scikit-learn
  dev_version: 1.5.1
  version_requirements: <1.8
  tags:
    - build_essential
- name: scipy
  dev_version: 1.11.3
  version_requirements: '>=1.9,<2'
- name: sentencepiece
  dev_version: 0.1.99
  version_requirements: '>=0.1.95,<0.2.0'
  requirements_extra_tags:
    - transformers
    - llm
- name: sentence-transformers
  dev_version: 2.7.0
  version_requirements: '>=2.7.0,<4'
  requirements_extra_tags:
    - transformers
    - llm
- name_conda: snowflake-connector-python
  name_pypi: snowflake-connector-python[pandas]
  dev_version: 3.17.3
  version_requirements: '>=3.17.3,<4'
- name: snowflake.core
  dev_version: 1.0.5
  version_requirements: '>=1.0.2,<2'
- name: snowflake-snowpark-python
  dev_version: 1.28.0
  version_requirements: '>=1.17.0,<2,!=1.26.0'
- name: sphinx
  dev_version: 5.0.2
- name: starlette
  dev_version: 0.27.0
- name: sqlparse
  dev_version: 0.4.4
  version_requirements: '>=0.4,<1'
- name: tensorflow
  dev_version: 2.17.0
  version_requirements: '>=2.17.0,<3'
  requirements_extra_tags:
    - tensorflow
    - keras
- name_conda: tokenizers
  dev_version_conda: 0.15.1
  version_requirements: '>=0.15.1,<1'
  requirements_extra_tags:
    - transformers
- name_pypi: tokenizers
  dev_version_pypi: 0.21.0
  version_requirements: '>=0.15.1,<1'
  requirements_extra_tags:
    - llm
- name: toml
  dev_version: 0.10.2
  tags:
    - build_essential
- name: torchdata
  dev_version_conda: 0.6.1
  dev_version_pypi: 0.8.0
  version_requirements: '>=0.4,<1'
  requirements_extra_tags:
    - torch
    - llm
- name_conda: transformers
  dev_version_conda: 4.39.3
  version_requirements: '>=4.39.3,<5,!=4.51.3'
  requirements_extra_tags:
    - transformers
- name_pypi: transformers
  dev_version_pypi: 4.51.0
  version_requirements: '>=4.39.3,<5,!=4.51.3'
  requirements_extra_tags:
    - llm
- name: types-requests
  dev_version: 2.30.0.0
- name: types-protobuf
  dev_version: 4.23.0.1
- name: types-PyYAML
  dev_version: 6.0.12.12
- name: keras
  dev_version: 3.6.0
  version_requirements: '>=2.0.0,<4'
  requirements_extra_tags:
    - keras
- name: types-toml
  dev_version: 0.10.8.6
  tags:
    - build_essential
- name: typing-extensions
  dev_version: 4.11.0
  version_requirements: '>=4.1.0,<5'
- name: xgboost
  dev_version: 2.1.4
  version_requirements: <4
  tags:
    - build_essential
- name: werkzeug
  dev_version: 2.3.8
- name: cachetools
  dev_version: 5.3.3
  version_requirements: '>=3.1.1,<6'
- name: pytimeparse
  dev_version: 1.1.8
  version_requirements: '>=1.1.8,<2'
- name: altair
  dev_version: 5.5.0
  version_requirements: '>=5,<6'
  requirements_extra_tags:
    - altair
- name: streamlit
  dev_version: 1.44.1
  version_requirements: '>=1.30.0,<2'
  requirements_extra_tags:
    - streamlit
- name: platformdirs
  dev_version: 4.3.7
  version_requirements: <5
- name: tqdm
  dev_version: 4.67.1
  version_requirements: <5
- name: cmdstanpy
  dev_version: 1.1.0

# Below are pip only external packages
- name_pypi: --extra-index-url https://pypi.org/simple
  dev_version_pypi: ''
- name_pypi: accelerate
  dev_version_pypi: 0.26.0
  requirements_extra_tags:
    - transformers
    - llm
- name_pypi: tf-keras
  dev_version_pypi: 2.17.0
  tags:
    - build_test_env
  requirements_extra_tags:
    - keras
- name_pypi: types-cachetools
  dev_version_pypi: 4.2.2
