"""Test tiers for autogenerated modeling estimators."""

load("//snowflake/ml/modeling/calibration:estimators_info.bzl", calibration_estimators = "estimator_info_list")
load("//snowflake/ml/modeling/cluster:estimators_info.bzl", cluster_estimators = "estimator_info_list")
load("//snowflake/ml/modeling/compose:estimators_info.bzl", compose_estimators = "estimator_info_list")
load("//snowflake/ml/modeling/covariance:estimators_info.bzl", covariance_estimators = "estimator_info_list")
load("//snowflake/ml/modeling/cross_decomposition:estimators_info.bzl", cross_decomposition_estimators = "estimator_info_list")
load("//snowflake/ml/modeling/decomposition:estimators_info.bzl", decomposition_estimators = "estimator_info_list")
load("//snowflake/ml/modeling/discriminant_analysis:estimators_info.bzl", discriminant_analysis_estimators = "estimator_info_list")
load("//snowflake/ml/modeling/ensemble:estimators_info.bzl", ensemble_estimators = "estimator_info_list")
load("//snowflake/ml/modeling/feature_selection:estimators_info.bzl", feature_selection_estimators = "estimator_info_list")
load("//snowflake/ml/modeling/gaussian_process:estimators_info.bzl", gaussian_process_estimators = "estimator_info_list")
load("//snowflake/ml/modeling/impute:estimators_info.bzl", impute_estimators = "estimator_info_list")
load("//snowflake/ml/modeling/isotonic:estimators_info.bzl", isotonic_estimators = "estimator_info_list")
load("//snowflake/ml/modeling/kernel_approximation:estimators_info.bzl", kernel_approximation_estimators = "estimator_info_list")
load("//snowflake/ml/modeling/kernel_ridge:estimators_info.bzl", kernel_ridge_estimators = "estimator_info_list")
load("//snowflake/ml/modeling/lightgbm:estimators_info.bzl", lightgbm_estimators = "estimator_info_list")
load("//snowflake/ml/modeling/linear_model:estimators_info.bzl", linear_model_estimators = "estimator_info_list")
load("//snowflake/ml/modeling/manifold:estimators_info.bzl", manifold_estimators = "estimator_info_list")
load("//snowflake/ml/modeling/mixture:estimators_info.bzl", mixture_estimators = "estimator_info_list")
load("//snowflake/ml/modeling/model_selection:estimators_info.bzl", model_selection_estimators = "estimator_info_list")
load("//snowflake/ml/modeling/multiclass:estimators_info.bzl", multiclass_estimators = "estimator_info_list")
load("//snowflake/ml/modeling/multioutput:estimators_info.bzl", multioutput_estimators = "estimator_info_list")
load("//snowflake/ml/modeling/naive_bayes:estimators_info.bzl", naive_bayes_estimators = "estimator_info_list")
load("//snowflake/ml/modeling/neighbors:estimators_info.bzl", neighbors_estimators = "estimator_info_list")
load("//snowflake/ml/modeling/neural_network:estimators_info.bzl", neural_network_estimators = "estimator_info_list")
load("//snowflake/ml/modeling/preprocessing:estimators_info.bzl", preprocessing_estimators = "estimator_info_list")
load("//snowflake/ml/modeling/semi_supervised:estimators_info.bzl", semi_supervised_estimators = "estimator_info_list")
load("//snowflake/ml/modeling/svm:estimators_info.bzl", svm_estimators = "estimator_info_list")
load("//snowflake/ml/modeling/tree:estimators_info.bzl", tree_estimators = "estimator_info_list")
load("//snowflake/ml/modeling/xgboost:estimators_info.bzl", xgboost_estimators = "estimator_info_list")

NO_TEST = "none"
WAREHOUSE_CAPABILITY_TEST = "warehouse_capability"

# Autogenerated estimators share one wrapper implementation. Keep warehouse coverage for
# representatives that exercise distinct inference methods, trainers, or template branches.
MODELING_TEST_TIERS = {
    "HistGradientBoostingRegressor": WAREHOUSE_CAPABILITY_TEST,  # nondeterministic result comparison
    "KMeans": WAREHOUSE_CAPABILITY_TEST,  # unsupervised fit_predict
    "KNeighborsClassifier": WAREHOUSE_CAPABILITY_TEST,  # kneighbors structured output
    "LGBMClassifier": WAREHOUSE_CAPABILITY_TEST,  # LightGBM packaging
    "LinearRegression": WAREHOUSE_CAPABILITY_TEST,  # regression
    "LogisticRegressionCV": WAREHOUSE_CAPABILITY_TEST,  # classification and decision_function
    "MultiTaskLasso": WAREHOUSE_CAPABILITY_TEST,  # multi-target labels
    "OneVsRestClassifier": WAREHOUSE_CAPABILITY_TEST,  # meta-estimator
    "PolynomialFeatures": WAREHOUSE_CAPABILITY_TEST,  # transform-only estimator
    "RandomForestClassifier": WAREHOUSE_CAPABILITY_TEST,  # ensemble and sample weights
    "SVC": WAREHOUSE_CAPABILITY_TEST,  # predict_proba
    "SparsePCA": WAREHOUSE_CAPABILITY_TEST,  # custom output column count
    "VotingClassifier": WAREHOUSE_CAPABILITY_TEST,  # multidimensional transform output
    "XGBRegressor": WAREHOUSE_CAPABILITY_TEST,  # XGBoost packaging
}

_ALL_ESTIMATOR_CLASS_NAMES = {
    estimator.class_name: None
    for estimator_info_list in [
        calibration_estimators,
        cluster_estimators,
        compose_estimators,
        covariance_estimators,
        cross_decomposition_estimators,
        decomposition_estimators,
        discriminant_analysis_estimators,
        ensemble_estimators,
        feature_selection_estimators,
        gaussian_process_estimators,
        impute_estimators,
        isotonic_estimators,
        kernel_approximation_estimators,
        kernel_ridge_estimators,
        lightgbm_estimators,
        linear_model_estimators,
        manifold_estimators,
        mixture_estimators,
        model_selection_estimators,
        multiclass_estimators,
        multioutput_estimators,
        naive_bayes_estimators,
        neighbors_estimators,
        neural_network_estimators,
        preprocessing_estimators,
        semi_supervised_estimators,
        svm_estimators,
        tree_estimators,
        xgboost_estimators,
    ]
    for estimator in estimator_info_list
}

def validate_modeling_test_tiers():
    """Fails the build when a tier entry cannot select a test target.

    An entry naming a class that no estimator list declares would otherwise fall back to
    NO_TEST, dropping that capability's coverage without any error.
    """
    for class_name, test_tier in MODELING_TEST_TIERS.items():
        if class_name not in _ALL_ESTIMATOR_CLASS_NAMES:
            fail("Modeling test tier '{}' names an estimator that no longer exists.".format(class_name))
        if test_tier != WAREHOUSE_CAPABILITY_TEST:
            fail("Modeling test tier for '{}' must be '{}', got '{}'.".format(
                class_name,
                WAREHOUSE_CAPABILITY_TEST,
                test_tier,
            ))
