from enum import Enum


class TargetPlatform(Enum):
    WAREHOUSE = "WAREHOUSE"
    SNOWPARK_CONTAINER_SERVICES = "SNOWPARK_CONTAINER_SERVICES"


WAREHOUSE_ONLY = [TargetPlatform.WAREHOUSE]
SNOWPARK_CONTAINER_SERVICES_ONLY = [TargetPlatform.SNOWPARK_CONTAINER_SERVICES]
BOTH_WAREHOUSE_AND_SNOWPARK_CONTAINER_SERVICES = [TargetPlatform.WAREHOUSE, TargetPlatform.SNOWPARK_CONTAINER_SERVICES]
