from enum import Enum


class Task(Enum):
    UNKNOWN = "UNKNOWN"
    TABULAR_BINARY_CLASSIFICATION = "TABULAR_BINARY_CLASSIFICATION"
    TABULAR_MULTI_CLASSIFICATION = "TABULAR_MULTI_CLASSIFICATION"
    TABULAR_REGRESSION = "TABULAR_REGRESSION"
    TABULAR_RANKING = "TABULAR_RANKING"
