load("//bazel:py_rules.bzl", "py_binary")

package(default_visibility = [
    "//bazel:snowml_public_common",
])

py_binary(
    name = "run_synthetic_data_generator",
    srcs = [
        "run_synthetic_data_generator.py",
    ],
    deps = [
        "//snowflake/ml/_internal/utils:connection_params",
        "//snowflake/ml/feature_store/_internal:synthetic_data_generator",
    ],
)
