estimator_info_list = [
    struct(class_name = "ARDRegression", normalized_class_name = "ard_regression"),
    struct(class_name = "BayesianRidge", normalized_class_name = "bayesian_ridge"),
    struct(class_name = "ElasticNet", normalized_class_name = "elastic_net"),
    struct(class_name = "ElasticNetCV", normalized_class_name = "elastic_net_cv"),
    struct(class_name = "GammaRegressor", normalized_class_name = "gamma_regressor"),
    struct(class_name = "HuberRegressor", normalized_class_name = "huber_regressor"),
    struct(class_name = "Lars", normalized_class_name = "lars"),
    struct(class_name = "LarsCV", normalized_class_name = "lars_cv"),
    struct(class_name = "Lasso", normalized_class_name = "lasso"),
    struct(class_name = "LassoCV", normalized_class_name = "lasso_cv"),
    struct(class_name = "LassoLars", normalized_class_name = "lasso_lars"),
    struct(class_name = "LassoLarsCV", normalized_class_name = "lasso_lars_cv"),
    struct(class_name = "LassoLarsIC", normalized_class_name = "lasso_lars_ic"),
    struct(class_name = "LinearRegression", normalized_class_name = "linear_regression"),
    struct(class_name = "LogisticRegression", normalized_class_name = "logistic_regression"),
    struct(class_name = "LogisticRegressionCV", normalized_class_name = "logistic_regression_cv"),
    struct(class_name = "MultiTaskElasticNet", normalized_class_name = "multi_task_elastic_net"),
    struct(class_name = "MultiTaskElasticNetCV", normalized_class_name = "multi_task_elastic_net_cv"),
    struct(class_name = "MultiTaskLasso", normalized_class_name = "multi_task_lasso"),
    struct(class_name = "MultiTaskLassoCV", normalized_class_name = "multi_task_lasso_cv"),
    struct(class_name = "OrthogonalMatchingPursuit", normalized_class_name = "orthogonal_matching_pursuit"),
    struct(class_name = "PassiveAggressiveClassifier", normalized_class_name = "passive_aggressive_classifier"),
    struct(class_name = "PassiveAggressiveRegressor", normalized_class_name = "passive_aggressive_regressor"),
    struct(class_name = "Perceptron", normalized_class_name = "perceptron"),
    struct(class_name = "PoissonRegressor", normalized_class_name = "poisson_regressor"),
    struct(class_name = "RANSACRegressor", normalized_class_name = "ransac_regressor"),
    struct(class_name = "Ridge", normalized_class_name = "ridge"),
    struct(class_name = "RidgeCV", normalized_class_name = "ridge_cv"),
    struct(class_name = "RidgeClassifier", normalized_class_name = "ridge_classifier"),
    struct(class_name = "RidgeClassifierCV", normalized_class_name = "ridge_classifier_cv"),
    struct(class_name = "SGDClassifier", normalized_class_name = "sgd_classifier"),
    struct(class_name = "SGDOneClassSVM", normalized_class_name = "sgd_one_class_svm"),
    struct(class_name = "SGDRegressor", normalized_class_name = "sgd_regressor"),
    struct(class_name = "TheilSenRegressor", normalized_class_name = "theil_sen_regressor"),
    struct(class_name = "TweedieRegressor", normalized_class_name = "tweedie_regressor"),
]

snowpark_pandas_estimator_info_list = estimator_info_list
